### ISSUE TITLE
App beta through Testflight

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-ios#1]
When do you think it will be possible to start an app beta through Testflight? That will make testing, helping design, and find issues much easier early on. :)

@ivansss @nextcloud/ios

**Comment by Ivansss** [comment]
I think it will make sense once we have the basic implementation of the calling feature, hopefully next week :)

**Comment by jancborchardt** [comment]
@Ivansss any news? :)

**Comment by Ivansss** [comment]
@jancborchardt Calling feature #2  is still WIP and not ready for testing yet.

**Comment by johnfelipe** [comment]
when can i test in ios 10.3?

**Comment by jancborchardt** [comment]
@johnfelipe as @Ivansss said, the pull reqeust at https://github.com/nextcloud/spreed-ios/pull/2 is still work in progress. If you have a testing/developer setup, any review is appreciated. :)

**Comment by johnfelipe** [comment]
Can u share iOS app for test?

**Comment by johnfelipe** [comment]
hi bro, can u share instalable app?, i cant compile only install and test

**Comment by Ivansss** [comment]
hi @johnfelipe , version 0.1 is already on TestFlight.
I could send you an invitation to test the app when it's ready for external testers (in a few days).
Should I send that invitation to the gmail account you have in your github profile?

**Comment by marinofaggiana** [comment]
@Ivansss please change icon app, for Apple is not possible to have 2 App with same icon ;)

**Comment by johnfelipe** [comment]
Yes bro, send me to my Gmail, tnks

**Comment by andyxheli** [comment]
@Ivansss can i please get a test flight invitation?
