### ISSUE TITLE
Not working with self signed certificate.

### ISSUE THREAD

**Issue by mrlochis** [nextcloud/talk-ios#109]
After entering server "https//........com:8443" i get the message:

"Nextcloud Talk app not found. Please check...."

I localized the error in ncapicontroller.m

![image](https://user-images.githubusercontent.com/30544635/40763087-b6585ef0-64a3-11e8-839b-1bd0980b6bcc.png)

The ios-nextcloud client and the android talk-app are working with self signed certificates.

Thank you.

**Comment by Ivansss** [comment]
Hi @mrlochis 
Are you running master branch?
If so, try running the latest stable release 1.3.2.
A dialog similar to this one should pop up when there is a self-sign certificate you need to trust after entering the server url.

![img_0153](https://user-images.githubusercontent.com/4638605/40775007-555b16f0-64c7-11e8-8eeb-b399fb6988e5.PNG)

**Comment by mrlochis** [comment]
on my iPhone 6 (iOS 11.3.1) i have installed Nextcloud Talk (1.3.2) from the Apple Appstore.
i have installed the latest version of nextcloud within docker on a mac mini and a self signed certificate (example from nextcloud docker).
i can connect to this nextcloud installation with the **nextcloud ios-client** and upload/download files successful. i also can connect from other macs with the nextcloud desktop app. at the first login in **nextcloud ios-client** i had to confirm the certificate (as shown in your screenshot).
but in **nextcloud talk-ios**  a popup to confirm the certificate was never shown. after entering the server (the _same_ as in **nextcloud ios-client**) and pressing the login button, evertime i got the message "Nextcloud app not found....". 
So i downloaded the master-branch today and had a look on the sources in the emulator. So i found the error (see screenshot)
thank you.

**Comment by Ivansss** [comment]
What version of Nextcloud Talk do you have installed in your Nextcloud instance?

**Comment by mrlochis** [comment]
nextcloud server version: 13.0.2.
i can connect from an android device with the **android-talk** app from the google play store successful.

**Comment by Ivansss** [comment]
Could you send me an email with your Nextcloud server url to `ivan AT nextcloud DOT com`?

**Comment by mrlochis** [comment]
**my steps to reproduce:**

iPhone: iPhone 6 iOS 11.4
iMac:  macOS 10.13.5
Android Tablet: Asus Zenpad Android 5.0
all devices used are in the same lan.

the local host name of my iMac is "iMac-2013.local":
![image](https://user-images.githubusercontent.com/30544635/41159611-605cebde-6b2d-11e8-8936-b93d6f487419.png)

i disabled the firewall on the iMac:
![image](https://user-images.githubusercontent.com/30544635/41160831-1880a8f6-6b31-11e8-862a-82d00c2a20d3.png)


now i made a brand new installation of docker on the iMac:
![bildschirmfoto 2018-06-08 um 15 00 52](https://user-images.githubusercontent.com/30544635/41159431-cea5c72e-6b2c-11e8-9616-18b35dba967f.png)

i made a factory reset on docker _"Reset to factory defaults"_.
![image](https://user-images.githubusercontent.com/30544635/41188144-bd057612-6bb9-11e8-977f-460f539f38a5.png)

i put the following files (without the .txt-extension) into the folder _~/nextcloud_docker/nginx_mariadb_selfsigned/_ and changed with _cd ~/nextcloud_docker/nginx_mariadb_selfsigned/_ into this directory. 
inside this directory i deleted a possibly available folder _docker_ with _rm -rd docker_ from a previous test  installation.
then i installed nextcloud with command _docker-compose up -d_ in terminal.
(nginx.conf.txt is original from https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy-self-signed-ssl/mariadb/fpm and the others files are modified versions from there):
[db.env.txt](https://github.com/nextcloud/talk-ios/files/2084445/db.env.txt)
[nginx.conf.txt](https://github.com/nextcloud/talk-ios/files/2084479/nginx.conf.txt)
[uploadsize.conf.txt](https://github.com/nextcloud/talk-ios/files/2084448/uploadsize.conf.txt)
[docker-compose.yml.txt](https://github.com/nextcloud/talk-ios/files/2084449/docker-compose.yml.txt)

![image](https://user-images.githubusercontent.com/30544635/41188362-50b64a06-6bbc-11e8-961f-b7292b9b5d1d.png)

then i finished my installation in safari (after accepting the certificate):
![image](https://user-images.githubusercontent.com/30544635/41159746-e7d4179a-6b2d-11e8-8fc3-de9c1c5c1e8b.png)

then i activated the "Groupware package" in nextcloud:
![image](https://user-images.githubusercontent.com/30544635/41159821-0b498624-6b2e-11e8-9cb2-e7409ba2aea2.png)

and did not change the default settings of talk:
![image](https://user-images.githubusercontent.com/30544635/41159848-2e0e1e54-6b2e-11e8-8e82-6d59163d7554.png)



then i opened the site in safari on my iPhone, accepted the certificate and i can login:
![18-06-08 15-43-29 0467](https://user-images.githubusercontent.com/30544635/41161366-e6ee06ec-6b32-11e8-8ade-ae01611b0ec2.png)
![18-06-08 15-43-45 0468](https://user-images.githubusercontent.com/30544635/41161368-e8270b9e-6b32-11e8-8d87-1bf4dba6ad0c.png)



then i added a new account to the nextcloud-ios - app (**NOT THE TALK-IOS APP!**):
![18-06-08 15-45-55 0469](https://user-images.githubusercontent.com/30544635/41161459-3d9a3fb0-6b33-11e8-89bc-806c4b3935de.png)
![18-06-08 15-46-23 0470](https://user-images.githubusercontent.com/30544635/41162393-05cfc520-6b36-11e8-8f06-9b0c830e4ca8.png)



then i try to login to the TALK-IOS App (Nextcloud Talk). After entering the same url
https://imac-2013.local and pressing the login button i got following message:
![18-06-08 15-49-07 0471](https://user-images.githubusercontent.com/30544635/41161587-a64b18e0-6b33-11e8-8ae7-fce78a27567e.png)

then i tried to login with an Android - Device.
I could login to the nextcloud-ios app **AND** the talk-ios app with success (after accepting the certificate).

this was a test in lan only. but with the other one, i can connect via internet and the windows-desktop app, the macOS desktop app and the nextcloud-ios app (NOT THE TALK-IOS APP) successful.

**Comment by Ivansss** [comment]
Let's share what we discussed by email:
What I received when trying to connect to your server with Safari through `https`:
```
400 Bad Request
The plain HTTP request was sent to HTTPS port
```
So it seems that something is not well configured in your server.

Nextcloud Talk iOS app follows ATS, while Nextcloud iOS app has an exemption for it (NSAllowsArbitraryLoads).
One of the requirements of ATS is that every connection should go trough HTTPS.
And here it seems that it's trying a HTTP request trough HTTPS.
Here the rest of [ATS requirements](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW57)
Maybe this helps?
https://stackoverflow.com/questions/8768946/dealing-with-nginx-400-the-plain-http-request-was-sent-to-https-port-error

**Comment by Ivansss** [comment]
Closing due to lack of feedback.

**Comment by rkempner** [comment]
> Nextcloud Talk iOS app follows ATS, while Nextcloud iOS app has an exemption for it (NSAllowsArbitraryLoads).

Why would you not just add this exemption for the Talk iOS app to avoid this problem? I'm having trouble getting the app to recognize my server even after installing the .pem to my device and trusting the root certificate. Why can't I just use my self signed cert on iOS Talk app? Works fine on Android.

Edit: My server requires HTTPS by the way
