### ISSUE TITLE
Not found openssl library files.

### ISSUE THREAD

**Issue by PawelLukasiak** [nextcloud/talk-ios#114]
I have same issue with linking openssl files.
'openssl/rsa.h' file not found
I think this is my local mistake.
How can I fix that?

**Comment by Ivansss** [comment]
I think there is some context missing here 😬 
Not clear what you mean by "same issue" but I guess you are trying to build the project.
How are you trying to build it?
openssl library and its headers should be under ThirdParty/openssl
Do you have the library and its headers there?

**Comment by PawelLukasiak** [comment]
"Some" issue :D Sorry for my mistake.
Exactly, I can't build the project, openssl is under ThirdParty / openssl.

**Comment by Ivansss** [comment]
@PawelLukasiak found the issue? :)
