### ISSUE TITLE
Emojis

### ISSUE THREAD

**Issue by mario** [nextcloud/talk-ios#123]
The app doesn't properly send the emojis so you get some weird chars back from the server :)

**Comment by Ivansss** [comment]
This has nothing to do with the app.
As discussed in https://github.com/nextcloud/spreed/issues/994, the problem is a missing emoji font in your system or browser.

**Comment by mario** [comment]
On iOS, really? At least for Android I was sending wrong characters to the server.

**Comment by thiphariel** [comment]
How do you explain that emojis are working great on others apps on iOS ? That certainly have to do with the app.
How the hell you wanna tweak font system on iOS ? (Don't troll or call Jailbreak) ...

**Comment by pagaille** [comment]
On my side I’m simply unable to send any emoji from the talk app.

**Comment by Ivansss** [comment]
Hi @pagaille,
You mean from the iOS app or the web app?

**Comment by pagaille** [comment]
Yep, the app. I if choose an Emoji using apple's dedicated keyboard it gets simply ignored. It's like nothing is sent when you press the send key.

**Comment by Ivansss** [comment]
So when you send a message with text + emojis, the text is visible but the emojis are not visible?

Do you use MySQL?
If that's the case take a look to https://docs.nextcloud.com/server/11/admin_manual/maintenance/mysql_4byte_support.html
Could be that your database can't store emojis.
