### ISSUE TITLE
Notify me later about this message

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-ios#1313]
- Overview ticket at https://github.com/nextcloud/spreed/issues/10075

---

The message menu should have an option:
* "Set reminder" > Submenu opens with following options
![grafik](https://github.com/nextcloud/spreed/assets/213943/ab511846-72ca-49f9-b56b-e7da92abf3b4)

## Required aka. MVP
- [x] Later today => 6pm
- [x] Tomorrow => 8am
- [x] This weekend => 8am Saturday
- [x] Next week => 8am Monday

## Optional

- [x] Custom date+time picker

**Comment by SystemKeeper** [comment]
@nickvergessen Just saw your edit here: I think that „This weekend“ and „Next week“ are highly confusing. For example when you add a reminder on a Saturday/Sunday „This weekend“ should not refer to the current weekend, but the next one?! I would prefer to use „Next Saturday“ and „Next Monday“ to make it more clear what we are trying to do here? (That’s what I extracted from the API doc)

**Comment by nickvergessen** [comment]
cc @nimishavijay (also for cross feature design)
