### ISSUE TITLE
Status bar text should be white in all views

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-ios#14]
Currently the status bar text is black in all views, which looks strange both in the blue header and in the call. It should be white instead, in all views.

@Ivansss

**Comment by jancborchardt** [comment]
@Ivansss whenever closing an issue, a quick comment if it was fixed or even better linking a pull request would be great. :)

**Comment by Ivansss** [comment]
@jancborchardt  🤔 It was linked to PR #22 before closing.

**Comment by jancborchardt** [comment]
@ivansss ah sorry, the mobile app I used to read this notifocation didn't show that :/

**Comment by Ivansss** [comment]
@jancborchardt no problem 😉
