### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by tiulpin** [nextcloud/talk-ios#166]
It would be nice to have a dark mode for the app.
https://developer.apple.com/documentation/uikit/uiuserinterfacestyle/dark?changes=latest_minor
Or at least have the same color scheme, which is imported by Nextcloud app from the server
![906e9b99-95b8-4377-84f4-739036110c95](https://user-images.githubusercontent.com/13538286/46995643-3bf7f800-d122-11e8-9676-812417edf330.png)

**Comment by jean-io** [comment]
iOS 13 has now an official dark mode. It would be nice to have a dark theme that toggle on and off depending on system settings.

**Comment by croessner** [comment]
I would like a dark mode, too 😊
