### ISSUE TITLE
CallKit

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-ios#17]
Just saw this blog post by the Riot team: https://medium.com/@RiotChat/communities-aka-groups-are-here-announcing-riot-web-0-13-riot-ios-0-6-and-riot-android-0-7-4-933cb193a28e

When you scroll down or search for »CallKit« you see a super nice integration with the OS through using the native ringer. Do we use that too? @Ivansss @marinofaggiana 

(Also cc @tobiasKaminsky for Android, just in case that exists there?)

**Comment by Ivansss** [comment]
Hi @jancborchardt ,
We already thought about CallKit 😄 We are currently investigating how to make it happen using our push notification system.

**Comment by mario** [comment]
@jancborchardt there is something on Android, much less nice, but works. Future however.
