### ISSUE TITLE
Multiple servers support

### ISSUE THREAD

**Issue by lars-sh** [nextcloud/talk-ios#170]
This is a feature request.

The iOS app does not seem to support conversations from multiple Nextcloud servers. Right now using multiple servers means logging out from the current and logging in to the next server while loosing push notifications.

**Comment by Ivansss** [comment]
You are right. Multi-account is not implemented yet.
Nevertheless this feature is on the roadmap and will come in one of the future releases :)

**Comment by lmamane** [comment]
Great. Appreciated.
