### ISSUE TITLE
improve call notification

### ISSUE THREAD

**Issue by ddi98** [nextcloud/talk-ios#172]
hi, why do not you let the notification ring several times when a phone call arrives?
it would be nice to even allow sending files from the app

**Comment by Ivansss** [comment]
We are currently working on improving notifications #171 
Once we have PushKit notifications we'll be able to use CallKit and have a very user friendly call notifications :)
Regarding sharing files, that's also on the roadmap.

**Comment by ddi98** [comment]
I did implement these functions by a developer! but the app is blocked with your codes

**Comment by ddi98** [comment]
when are these implementations foreseen?

**Comment by Ivansss** [comment]
What do you mean by...?

> but the app is blocked with your codes

**Comment by Ivansss** [comment]
> when are these implementations foreseen?

PushKit notifications are planned to be released soon (this year)

**Comment by ddi98** [comment]
my developer said that even if he rewrote the code, without your permission the application can not work

**Comment by ddi98** [comment]
speaks of a server-level limitation

**Comment by Ivansss** [comment]
Well, I think I know what you mean.
You won't be able to receive push notifications from a Nextcloud instance when the app is not signed with our certificates.
So I think you should disable Push Notifications from Capabilities in order to build the project.

**Comment by ddi98** [comment]
the problem is another, my change was made right on the notifications!

**Comment by ddi98** [comment]
even sending photos and files from the application does not happen without your certificates

**Comment by Ivansss** [comment]
Sending photos and files is not implemented yet.

**Comment by ddi98** [comment]
I did implement this function, but the programmer told me that it is not possible to send because of signatures

**Comment by mario** [comment]
@ddi98 sending files and photos has nothing to do with "our" certificates. Anyway, closing as duplicate of #17 :)

**Comment by Ivansss** [comment]
You can always send a pull request with your changes :)
But sending files and photos will require changes not only in this app but also in the server side.
