### ISSUE TITLE
Nextcloud server not found

### ISSUE THREAD

**Issue by maciejj** [nextcloud/talk-ios#173]
Hi!

I downloaded the app, and after providing an address to my nextloud server it gives an error "Nextcloud server not found". The https is enabled on the server side (with a self signed certificate) and it seems to work in the webbrowser and nextcloud client on iphone. However nextcloud talk app doesn't connect.  

ios nextcloud talk app version: 3.0.1
nextcloud server version: 14.0.3

**Comment by mario** [comment]
Hello. Can you try this please? :)

 Settings -> General -> About -> Certificate Trust Settings, and there is a section called "ENABLE FULL TRUST FOR ROOT CERTIFICATES".

**Comment by maciejj** [comment]
Thank you for the reply. Unfortunately I don't have such option OS version 11.4.1 (15G77)
![img_6819](https://user-images.githubusercontent.com/9079650/47458500-b1f60200-d7a7-11e8-8f4d-ffacf69f731f.PNG)

Should I udpate my to iOS 12.0.1 to enable it  ?

**Comment by Ivansss** [comment]
Could you send me an email to `ivan AT nextcloud.com` with the url of your NC server?

**Comment by maciejj** [comment]
Sent

**Comment by maciejj** [comment]
As @Ivansss suggested my self signed certificate somehow didn't satisfy the ATS requirements (https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW57) 
I updated my local openssl, generated new certificate and forced TLS=1.2 in apache but still couldn't make it work. 

I gave up playing with self-signed certificates and generated one using certbot (https://certbot.eff.org/). It works without any problems now.
