### ISSUE TITLE
Customize the nextcloud talk application

### ISSUE THREAD

**Issue by ddi98** [nextcloud/talk-ios#174]
Hi, I would be interested in making me customize and add features to the "nextcloud talk" app both for ios and for android "obviously paying the job" and possible?

Thank you and good day

**Comment by karlitschek** [comment]
what do you mean with 'paying the job' ?

**Comment by ddi98** [comment]
I mean I'm going to pay the programmer who will make these changes to me

**Comment by nickvergessen** [comment]
Please contact our Sales team for information:
https://nextcloud.com/enterprise/buy/
