### ISSUE TITLE
Crash when joining call (video+audio)

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/talk-ios#188]
When trying to join a call (happens on video and audio likewise), the call window comes up for a split second, then the app crashes.

This happens at 100% of my tests on a Nextcloud server with Talk MCU installed and at least 3 times on a non-MCU instance (after 3 crashes, the call finally works).

App version 3.2.0 on iOS 12.1.2

**Comment by Ivansss** [comment]
I couldn't reproduce this issue.
Could you describe the joining process a bit more? :)

- Are you joining the call following a push notification or pressing the call button in a conversation?
- Is there already some participants in the call when you join?
- Is any of these participants a guest?

**Comment by Ivansss** [comment]
@wiswedel Can you still reproduce this issue with version 3.2.1?

**Comment by wiswedel** [comment]
3.2.2 looks good so far! 👏👏

**Comment by Ivansss** [comment]
Also there is a bugfix for the external signaling server that will fix some connection issues when resuming client sessions.
