### ISSUE TITLE
Icon with new background

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-ios#19]
Here’s the new icon with the updated background:
https://github.com/nextcloud/promo/blob/master/Specific%20designs/icon-talk-ios.svg

Also adjusted the regular app icon:
https://github.com/nextcloud/promo/blob/master/Specific%20designs/icon-ios.svg

cc @Ivansss @marinofaggiana

**Comment by marinofaggiana** [comment]
@jancborchardt the second is the new icon app for iOS Nextcloud ?

**Comment by Ivansss** [comment]
@marinofaggiana just in case you need a quick way to generate app icons:
https://github.com/nextcloud/talk-ios/blob/master/docs/Generate-app-icons.md

**Comment by marinofaggiana** [comment]
@jancborchardt please download beta testFlight for test Nextcloud with new icon
