### ISSUE TITLE
Notifications don't work anymore

### ISSUE THREAD

**Issue by SteOtt** [nextcloud/talk-ios#194]
Notifications don't work on talk-ios. It does work on talk-android and it did work on talk-ios in the past.

I'm not 100% sure but I think it stopped working with the latest ios update (12.1.2).

I have nextcloud 15.0.2 and talk-ios 3.2.1 installed.

**Comment by Ivansss** [comment]
The iOS version update shouldn't be a problem.
Could you try to re-login with your account in the app?
What type (chat, call, invitation) of notifications are missing?

**Comment by SteOtt** [comment]
Thanks for you quick answer.

I did the following:
- logout from the app
- uninstall the app
- reboot the device
- re-install the app
- re-login into the app

this solved the issue. Now I get notifications again.

Only logging out and make a re-login didn't work.

An interesting question would be what caused this issue...

**Comment by Ivansss** [comment]
Interesting... 🤔 
When logging out, the app should remove the push notification token stored in the Keychain.
Then when logging in again, the app should subscribe again to receive push notifications.
I will investigate what could cause your situation.
Anyways, happy to hear that it works for you now :)
Thanks for your report!
