### ISSUE TITLE
photo sharing support

### ISSUE THREAD

**Issue by DeeeeLAN** [nextcloud/talk-ios#198]
Hi, it seems current photo sharing support is limited to nonexistent. I can't share anything from the app, and from the web, the share option just inserts a link.

I would love to see native sharing in the thread, with an option for all the photos uploaded to be stored in a 'mobile uploads' or 'talk' folder in nextcloud. Also the ability to view the photos within the app. Being able to insert photos from nextcloud seemlessly would be amazing as well.

**Comment by Ivansss** [comment]
This feature is in the roadmap :)
Some server implementation is needed first.
You can follow it https://github.com/nextcloud/spreed/issues/1129

**Comment by DeeeeLAN** [comment]
Thanks, that looks great. You keep mentioning this 'roadmap', but I don't see anything in the Projects for this repo. Are you basing it off the server roadmap, or is it just a roadmap in your head? I would be interested in seeing what features are planned and upcoming, estimated timelines, etc. if you wanted to flesh out the roadmap online. :)

**Comment by Ivansss** [comment]
Mobile clients (Android and iOS) always try to keep feature parity with the web client and between them.

You can follow our roadmap here: https://github.com/nextcloud/spreed/projects/1

**Comment by SystemKeeper** [comment]
https://github.com/nextcloud/spreed/issues/1129 is implemented 🥳

**Comment by SystemKeeper** [comment]
Hey @Ivansss, just wanted to know, if this is on the roadmap? Thx!

**Comment by Ivansss** [comment]
Hi @SystemKeeper :) This feature is in the roadmap for the next major release (Talk v10.0)

**Comment by SystemKeeper** [comment]
Working with v10. Thanks @Ivansss !

**Comment by DeeeeLAN** [comment]
This is much nicer. What about photo previews in the app itself, instead of making you jump to the nextcloud app to view?
