### ISSUE TITLE
CallKit Video 

### ISSUE THREAD

**Issue by gt2416** [nextcloud/talk-ios#200]
With the new callkit support on iOS I cant receive video calls anymore. Even if I initiate a video call it ends up being a audio call. Both people can see themselves as a video call but they cant see the other person.
I am running Nextcloud 15.0.4 and latest version of the iOS app. I am using my own personal turnserver on FreeBSD 12. It has been working since the update. It uses the pkg turnserver.

**Comment by Ivansss** [comment]
Call functionality has changed a bit with CallKit.

If `user A` calls `user B` using video and `user B` device is locked, `user B` will see a incoming call from `user A`.

When `user B` picks up the call, its device will remain locked and `user B` will see the following screen.

![img_0198](https://user-images.githubusercontent.com/4638605/52936661-20fdf480-335d-11e9-8cbf-7863a5b7b01c.PNG)

During this time, `user A` and. `user B` can only hear each other.

If `user B` wants to see and be seeing by `user A`, `user B` needs to tap the 'video' button and unlock the device.

After that, Talk app will be opened and the following dialog will be presented.

![img_0199](https://user-images.githubusercontent.com/4638605/52936801-a2558700-335d-11e9-83b0-2699b5f3b2a8.PNG)

If `user B` accepts to enable the video, the call will be interrupted for a few seconds and after that `user A` and `user B` will be able to see each other.

**Comment by gt2416** [comment]
I still cant get it to work. Once I enable video call, the call disconnects for a few seconds and then it says waiting for user as if they disconnected.  It NEVER reconnects. I have tried initiating video from both clients and same result. My turnserver config is
```
listening-port=8879
fingerprint
use-auth-secret
static-auth-secret=somesecret
realm=mydomain.com
total-quota=100
bps-capacity=0
stale-nonce
no-loopback-peers
no-multicast-peers
```
Edit: NVM please close this, it was a firewall issue.

**Comment by Ivansss** [comment]
> Edit: NVM please close this, it was a firewall issue.

Happy to hear that you found the issue and it is working now :)
