### ISSUE TITLE
Notification support?

### ISSUE THREAD

**Issue by DeeeeLAN** [nextcloud/talk-ios#201]
I don’t appear to receive notifications when new chat messages are sent. Is this a known issue?

**Comment by Ivansss** [comment]
Notifications on every new chat message are sent by default in one2one conversations.
In group conversations, notifications are sent only on mentions by default.

There is an option to change the notification level on every conversation:

- Always
- On mention
- Never

Could you tell us in which type of conversation you are missing the notifications? :)

**Comment by DeeeeLAN** [comment]
Ah, now that you say that, I do remember reading that somewhere. I wonder if it could be made more obvious somehow like an icon on the list indicating notification settings, or some sort of onboarding.

**Comment by Ivansss** [comment]
You are right, it is not really obvious.
We should think about some UI for that.
Closing this issue in favor of #202
