### ISSUE TITLE
Respect safe area on XS Max

### ISSUE THREAD

**Issue by helmut72** [nextcloud/talk-ios#218]
Respect safe area on iPhone XS Max. Textbox ("New message") fills the whole screen in landscape. The Textbox is under the notch when writing messages.

**Comment by Ivansss** [comment]
Thanks for the report @helmut72, this bug will be fixed in one of the next releases.

**Comment by Ivansss** [comment]
Fixed in b966b1d87e4f54f5f3130b06c0abf38ec2371f64.
This bug fix will be included in the next release.
