### ISSUE TITLE
Improvement: make single emojis bigger 

### ISSUE THREAD

**Issue by FramboisePi** [nextcloud/talk-ios#220]
Hello,

I have a suggestion. We could make messages bigger when they contain only emojis.

On macOS or iOS, if there is one, two or three emojis in a message there are bigger and not on a blue background.
On the contrary, if the message contains text or more than 3 emojis, it looks like a classic message.
<img width="165" alt="Capture d’écran 2019-04-21 à 11 42 52" src="https://user-images.githubusercontent.com/25133304/56469920-27354d80-6440-11e9-8f6e-83b12dbef45f.png">

I think it would be better on Talk if a similar idea was implemented.
Currently it looks like this:
<img width="89" alt="Capture d’écran 2019-04-21 à 11 43 56" src="https://user-images.githubusercontent.com/25133304/56469921-2d2b2e80-6440-11e9-84cb-31bbd0d6fe67.png">

**Comment by FramboisePi** [comment]
What do you think?
Is this a feature we need to add on Talk server or do we need to implement it on the iOS application too?

I opened an issue on Talk [Talk#1744](https://github.com/nextcloud/spreed/issues/1744). Should I close this one?

**Comment by Ivansss** [comment]
As @nickvergessen mentioned in https://github.com/nextcloud/spreed/issues/1744, this is already the case on the android [app](https://github.com/nextcloud/talk-android/) but not on the web and iOS apps.
Leave this issue open and we'll update it when this feature is implemented on iOS :)

**Comment by FramboisePi** [comment]
Ok, I was not sure about what to do.
Thank you for your answer.
