### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by croessner** [nextcloud/talk-ios#229]
Is there some chance to get multi language support in this app?

I could translate stuff to German, if someone sends me files or points me to the right place.

Thanks

**Comment by Ivansss** [comment]
Hi @croessner,
Thanks for bringing this topic up.
It is planned to add multi language support. It will be done using transifex as other Nextcloud app does.
I will keep this issue open and update it when we add this project to transifex.
Then you could help us with the German translations :)

**Comment by Ivansss** [comment]
The app is already in transifex for translations :)
https://www.transifex.com/nextcloud/nextcloud/talk-ios/

**Comment by SystemKeeper** [comment]
Done per 10.1.0.
