### ISSUE TITLE
Can't Use http://domain To Connect The Server

### ISSUE THREAD

**Issue by ywwn** [nextcloud/talk-ios#230]
Default use https is ok, http://ip is ok also.
Just can't use http://domain and I find this time the app won't push any request to server.

**Comment by Ivansss** [comment]
Hi @YohaneWW,
Nextcloud Talk follows Apple's ATS as said in the Prerequisites section.
https://github.com/nextcloud/talk-ios/blob/master/README.md
So one of the ATS requirements is that every connection should be https.

**Comment by ywwn** [comment]
@Ivansss 
But Nextcloud can work right, wish it can follow ATS soon.

**Comment by Ivansss** [comment]
Yes, Nextcloud iOS app doesn't follow ATS at the moment.
