### ISSUE TITLE
No audible/visible notification with app in background but still in conversation

### ISSUE THREAD

**Issue by wjwoods** [nextcloud/talk-ios#233]
If I close (background) the IOS talk app while still in a conversation I don't receive any further notifications from that conversation.  If I re-open (foreground) the app, click the "<" button to go back to the main screen I start receiving notifications again when the app is in the background.  Is this expected behavior?  Just means I have to remember to leave the conversation screen before I close the app.

Nextcloud Talk IOS version 6.1.1
Nextcloud Server version 16.0.1
Nextcloud Talk Server version 6.0.2
Apple IOS version 12.3.1
iPhone 7

**Comment by Ivansss** [comment]
Hi @wjwoods,
Thanks for opening this issue.
This is a "know bug" that we are trying to fix.
I will leave this issue open and update it when there are news.

**Comment by fuzunspm** [comment]
Any update on this?

**Comment by uselpa** [comment]
Having the same issue with Nextcloud 15.0.11 and Nextcloud Talk for iOS 7.0.0. It's basically the only thing that keeps me from replacing my current messenger with Nextcloud Talk.

**Comment by Ivansss** [comment]
The bug fix for this issue will be included in the next release (Nextcloud Talk iOS 7.1.0)

**Comment by wjwoods** [comment]
Thanks!  Really appreciate all your work on this awesome app!
