### ISSUE TITLE
Autofill login fields from URL scheme

### ISSUE THREAD

**Issue by fvdm** [nextcloud/talk-ios#234]
I would like to make the app setup easier for our users by sharing a special link with them that takes care of the basics. This prevents typos and other mistakes. Example:

`nextcloudtalk://login?server=https://nextcloud.server.tld&username=theirname`

I searched the source code for references but it appears a url scheme is not yet implemented. Could you please look into this?

**Comment by Ivansss** [comment]
We know it might come a bit late, but this feature will be included in the next major version :)
@fvdm
