### ISSUE TITLE
Sign in form does not work

### ISSUE THREAD

**Issue by trusta** [nextcloud/talk-ios#236]
There is a problem with the sign in button.
When I click on it, nothing happen.

I watched access logs on my server and I saw no requests when I clicked.

I also tried with the android application and it worked.
![Nextcloud Talk](https://user-images.githubusercontent.com/7666444/59847134-fa2ee980-9361-11e9-893e-dfa3a90b7550.jpg)

Can you help me ? Please!

**Comment by Ivansss** [comment]
Hi @trusta,

Does your server fulfill the [ATS requirements](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW57) ? 
Also, you could take a look to https://github.com/nextcloud/talk-ios/issues/226

**Comment by trusta** [comment]
Hi @Ivansss 

Thank you for your help !
The problem was in the file `config/config.php`, with the fields :
```
'overwrite.cli.url' => 'https://cloud.myserver.com',
'overwritehost' => 'cloud.myserver.com'
'overwriteprotocol' => 'https',
```

**Comment by Ivansss** [comment]
Thanks for sharing how you solved it @trusta :)
