### ISSUE TITLE
Please provide the ability to write and read SMS

### ISSUE THREAD

**Issue by szaimen** [nextcloud/talk-ios#253]
Please provide the ability to write and read SMS.
If that was implemented, you would be able to chat with other contacts, that don't have a nextcloud-installation via nextcloud-talk. -> could be a killer-feature after [Federation](https://github.com/nextcloud/spreed/issues/21).
Using the IOS App as a Bridge, you also would be able to chat with other contacts over SMS from other platforms like the web-interface.
The operating principle then would be just like iMessage.

**Comment by SystemKeeper** [comment]
Hey @szaimen 
Apple does not allow apps to access sms or iMessage messages and according to some posts of Apple employees (for example: https://developer.apple.com/forums/thread/16685) it doesn’t look like it’s ever going to happen.
If I’m not missing something here (?!) I think we can close this issue as we’re unable to implement this?!
