### ISSUE TITLE
Passcode for added protection

### ISSUE THREAD

**Issue by sconway856** [nextcloud/talk-ios#263]
The NextCloud iOS application currently allows the user to set a pin to restrict access to the application content.  This same behavior would be beneficial to the NextCloud talk-ios application as well.  This will protect message content and conversation.  

I can help with a pull request.

**Comment by Ivansss** [comment]
> I can help with a pull request.

Pull requests are always welcome :)
You can ping me if you have any questions or join [our public Talk team conversation](https://cloud.nextcloud.com/call/c7fz9qpr)

**Comment by sconway856** [comment]
I followed the same code and approach from the nextcloud application:  
- The passcode on and off is referred to as "lock" in the settings
- Simply passcode refers to entering 6 number.  When "Weak passcode" in the settings is turned on (the default) then "Simply" mode is used.
- If the simply passcode is off and the "lock" is on, then a 64 alpha-numeric passcode is required.
- The passcode must be re-entered to "remove" the passcode.
- If the passcode is on and the weak setting is changed, thee original passcode must be entered followed by the new passcode and a confirmation of the new passcode.
- The mode of "simply" passcode is stored in the keychain "ncBlockCodeUseSimply"
- The passcode value is stored in the keychain value "ncBlockCode"

Here is a summary of my changes:
1. The code for the BKPasscodeView group and CCBKPasscode were copied from the nextcloud application.  
2. In NCSettingsController I added the block code and "simply" passcode variables. (Not sure this is really necessary).
3. In the settings view controller is all the logic for adding, removing, and switching the weak passcode (aka "simply")  on and off while the passcode is set.
4. Images were added for the dots on the simply screen and the switch for the weak password.

Please let me know if I should change anything in the patch file and I can re-send it.

[AddPasscode.txt](https://github.com/nextcloud/talk-ios/files/3839148/AddPasscode.txt)

**Comment by sconway856** [comment]
Oh I need to remove the changes to Info.plist  I just had those in so I could hit http instead of only https, and I see I can cleanup the loaded library changes.

**Comment by Ivansss** [comment]
Hi @sconway856,
Could you create a PR with that patch? :)
Then it will be easier to track your changes and also discuss them.
Thanks for your contribution 😊

**Comment by sconway856** [comment]
Do I need to have permission to push my branch?  When I tried to push I got a 403 error

**Comment by Ivansss** [comment]
Once you accept the invitation to join the organization, you should be able to push 😉

**Comment by Ivansss** [comment]
#265
