### ISSUE TITLE
IOS 13.2.3 app “Nextcloud server not found”

### ISSUE THREAD

**Issue by kissaway** [nextcloud/talk-ios#267]
The Android client can connect to the server and use it normally. But report on IOS client“Nextcloud server not found  please check that you entered the correct Nextcloud server addess.
![IMG_0598](https://user-images.githubusercontent.com/10624752/69848322-c531a600-12b4-11ea-9c79-26419830f87b.PNG)
”

**Comment by Ivansss** [comment]
Hi @kissaway,
Does your server fulfill Apple's [ATS requirements](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW57)?

**Comment by kissaway** [comment]
> Hi @kissaway,
> Does your server fulfill Apple's [ATS requirements](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW57)?

I don't know yet. Let me check it

**Comment by Ivansss** [comment]
Closing this issue for now.
Feel free to re-open it @kissaway if your server fulfills the ATS requirements and you still see that error message.
