### ISSUE TITLE
iOS 13.3 - Talk app does not respect group settings

### ISSUE THREAD

**Issue by nextra06** [nextcloud/talk-ios#270]
Expected behaviour
Talk app for iOS should display only the contacts / users allowed by the server (placed by admin in a particular group).

Actual behaviour
Talk app for iOS displays all contacts in contact list when the server is set to allow only members of Talk group to use Talk app.

Steps to reproduce
Install Nextcloud server 16.0.5 (Upgraded from 16.0.4)
Install & Enable Talk app
Create users
Create a group (viz - Office)
Put a few users in that group
Install Talk app
Check the contacts
iOS version
iOS 13.3

App version
7.1.1

Server configuration
Operating system:
Raspbian Buster (Raspberry Pi 4B 4GB)
Web server:
Apache 2
Database:
MySQL (Socket)
PHP version:
7.3.11
Nextcloud version: (see Nextcloud admin page)
16.0.5

**Comment by Ivansss** [comment]
This bug will be fixed in the next release (v8.0).
Thanks for your report @nextra06 :)
