### ISSUE TITLE
iOS app 

### ISSUE THREAD

**Issue by ghost** [nextcloud/talk-ios#28]
How can I download the app on ios devices ?

**Comment by mario** [comment]
Via App Store where it'll be released soon. Stay tuned for the announcement!

**Comment by ghost** [comment]
Is there a beta version ?

Sent from my iPhone 7 Plus

On Jan 10, 2018, at 9:23 AM, Mario Đanić <notifications@github.com<mailto:notifications@github.com>> wrote:


Via App Store which will be released soon. Stay tuned for announcement!

**Comment by mario** [comment]
Yes, but not something we advertise since stable will be out soon.

**Comment by ghost** [comment]
Do you mind adding me? I’d like to check it out

Sent from my iPhone 7 Plus

On Jan 10, 2018, at 9:29 AM, Mario Đanić <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, but not something we advertise since stable will be out soon.

**Comment by mario** [comment]
@Ivansss ^_^

**Comment by Ivansss** [comment]
@andyxh No problem 😄 just give us an email address and we will send you a Testflight invitation.

**Comment by ghost** [comment]
Do you have an email I can send it too ?

Sent from my iPhone 7 Plus

On Jan 10, 2018, at 9:59 AM, Ivan Sein <notifications@github.com<mailto:notifications@github.com>> wrote:


@andyxh<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fandyxh&data=02%7C01%7C%7C17509aee374d440fa3b108d55843294c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636511967834320963&sdata=0%2BTXNo3ql5gqJX8Kj2SpF8jJDPozpjMJmj5s5XagiCQ%3D&reserved=0> No problem 😄 just give us an email address and we will send you a Testflight invitation.

**Comment by mario** [comment]
ivan@nextcloud.com xD

**Comment by andyxh** [comment]
xhelia @ outlook dot com
