### ISSUE TITLE
Nextcloud Talk iOS app loading very slow

### ISSUE THREAD

**Issue by ChildLearningClub** [nextcloud/talk-ios#283]
### Steps to reproduce
Open iOS app and then a conversation. The conversations take about 1 minute to load. 

### Expected behaviour
That the conversations load quickly 

### Actual behaviour
Conversations load normally on desktop, and even within a mobile browser, but not within the Nextcloud Talk iOS app itself. This happened more recently I believe with either the Nextcloud hub or with the update before the most recent 8.1.0 which is also slow. Simply leaving a conversation and clicking back in takes another minute to load the conversation that I was just looking at. 

## Server configuration detail

**Operating system:** Linux 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64

**Webserver:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** mysql 10.1.44

**PHP version:** 

7.3.15
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** 18.0.1 - 18.0.1.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from docker release

**Where did you install Nextcloud from:** Docker

<details><summary>Signing status</summary>

Array
(
    [user_external] => Array
        (
            [INVALID_HASH] => Array
                (
                    [appinfo/info.xml] => Array
                        (
                            [expected] => 06b250c3a2c2ae01c8a2c4b963d6449c99645dca36ee197c3aa513fb7ac3e90e42dc1408ee6957408d85f9f9a973b8983719e9c15125d42211d43f0853c7bf75
                            [current] => e5da848ca44b3b60abb1c99a3d26455d78464f94ea1f5f522b07d642096a771dcde9a1a5289e271805292659edc42925a86b5d6ad22ffa98b79ecec5bfed69ff
                        )

                    [lib/smb.php] => Array
                        (
                            [expected] => 283a99667fd865e54423d575953423bc6e15862b7683885cb5675aafdb3b2cbc1400a1318ec81cdbd90ce827c3f839aa6daf6a0f6e3ac6bd2742947498dd14f9
                            [current] => 1c12005d92f88017564fb4135a532810aab33ffab22eac67c19501a59d213518e417cceb83f5e9ea4b448ea81fff3149da37eefb0100a61bce3140ce67f8decc
                        )

                )

        )

)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - bruteforcesettings: 1.5.0
 - calendar: 2.0.1
 - circles: 0.18.3
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.1.8
 - dav: 1.14.0
 - deck: 0.8.0
 - documentserver_community: 0.1.5
 - event_update_notification: 1.0.1
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_accesscontrol: 1.8.1
 - files_automatedtagging: 1.8.0
 - files_markdown: 2.2.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - mail: 1.1.2
 - metadata: 0.11.1
 - nextcloud_announcements: 1.7.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - onlyoffice: 4.1.4
 - passman: 2.3.5
 - photos: 1.0.0
 - previewgenerator: 2.2.0
 - provisioning_api: 1.8.0
 - registration: 0.4.7
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - spreed: 8.0.4
 - systemtags: 1.8.0
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflow_script: 1.3.1
 - workflowengine: 2.0.0
Disabled:
 - cms_pico
 - dicomviewer
 - drawio
 - encryption
 - files_external
 - files_pdfviewer
 - guests
 - impersonate
 - maps
 - password_policy
 - passwords
 - phonetrack
 - polls
 - privacy
 - recommendations
 - richdocuments
 - social
 - support
 - survey_client
 - user_ldap
 - user_saml

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "overwrite.cli.url": "https:\/\/share.oilsgift.com",
    "overwriteprotocol": "https",
    "htaccess.RewriteBase": "\/",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nextcloud.oilsgift.com",
        "share.oilsgift.com"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.1.3",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "ffmpeg": "\/usr\/bin\/ffmpeg",
    "enable_previews": true,
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\Movie",
        "OC\\Preview\\PDF",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\MP4"
    ],
    "filelocking.enabled": true,
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379,
        "password": "***REMOVED SENSITIVE VALUE***",
        "timeout": 1.5
    },
    "simpleSignUpLink.shown": false,
    "maintenance": false,
    "loglevel": 2,
    "updater.release.channel": "stable",
    "mail_sendmailmode": "smtp",
    "app_install_overwrite": [
        "passman",
        "dicomviewer",
        "issuetemplate",
        "spreed",
        "contacts"
    ],
    "theme": ""
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (iPhone; CPU iPhone OS 13_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Mobile/15E148 Safari/604.1

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by Ivansss** [comment]
Hi @Bellusterra 
There have been no changes regarding the loading of the conversation list or chat messages in the last versions.
A slow loading of the conversation list or chat messages could be due to a bad internet connection.
Did you notice which mobile internet connection you were using when experiencing this slow loads?

**Comment by ChildLearningClub** [comment]
Hi @Ivansss I must have changed something on my setup then, it’s consistently doing it. My internet speed is fast so it’s not that, I will have to dig a bit deeper, thank you for letting me know... kind of along the same lines it made me think that a cache would be a nice feature. If I’m correct it pulls from Nextcloud the whole conversation every time you go into the chat room again, I would think having something similar to what the Nextcloud app does with thumbnails and what apples native iMessage does, would be a great addition, plus things would load instantly, and being chat would not take up much memory on people’s devices... anyway I’ll have to open a new ticket for that. Thank you again.

**Comment by Ivansss** [comment]
We are working on the offline support (cache) feature :)

**Comment by ChildLearningClub** [comment]
Just to comment on this, the problem was solved by having initially disabling The brute force app. With ngnix reverse proxy all connections were comming from the same ip, making sure to put the correct nginx reverse proxy settings for ip forwarding solved the problem.
