### ISSUE TITLE
Chat cache

### ISSUE THREAD

**Issue by ChildLearningClub** [nextcloud/talk-ios#284]
As the conversations become larger caching to the local device might be of value. It would improve the load speed of conversation, even if marginally at times, but even if marginally any improvement would be good. In addition their could be the option to clear the cache of anything past 30 days or something to keep it lean with anything older being pulled in as normal when scrolling up to it?

**Comment by ChildLearningClub** [comment]
Thank you, just spent the last 5 minutes trying to figure out how to add the enhancement label with out success.

**Comment by Ivansss** [comment]
Talk iOS v9.0 comes with this feature :)
The option to clear cache is not there yet. Since we only store text at the moment, it shouldn't be a problem. An option to clear cache will come in a future release.

**Comment by ChildLearningClub** [comment]
Hi @Ivansss Thank you so much for the great work! You’re doing a great job. I’m excited to update to the latest version and see it in action.

**Comment by ChildLearningClub** [comment]
Wow!! Way faster now!! Used to have to wait each time for the conversations to load, what an improvement!

**Comment by Ivansss** [comment]
Thanks for your words @Bellusterra! :) Glad to hear that you like Talk iOS v9.0 :D
