### ISSUE TITLE
How use with my own NC instance?

### ISSUE THREAD

**Issue by johnfelipe** [nextcloud/talk-ios#30]
Pls tell me how use with my NC instance?

**Comment by Ivansss** [comment]
You would need to update your instance to the latest Nextcloud 13 beta release and also install the [Talk](https://apps.nextcloud.com/apps/spreed) app.
You could also wait to NC 13 official release, so you don't have to update your instance to a beta release.

**Comment by johnfelipe** [comment]
https://apps.nextcloud.com/apps/spreed

https://goo.gl/d2By3e

Is not possible use with NC 12?

**Comment by Ivansss** [comment]
> Is not possible use with NC 12?

Not the latest features neither the mobiles apps.

**Comment by johnfelipe** [comment]
`You could also wait to NC 13 official release`
When?

**Comment by Ivansss** [comment]
https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule
Soon 😄 (January 2018)

**Comment by johnfelipe** [comment]
Then will be in this month?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-01-12 2:54 GMT-05:00 Ivan Sein <notifications@github.com>:

**Comment by Ivansss** [comment]
> Then will be in this month?

Yes
