### ISSUE TITLE
Implement login via QR code

### ISSUE THREAD

**Issue by redm123** [nextcloud/talk-ios#305]
When I choose login with token I can enter name and token. I would expect that I can scan the QR code? But I don't see how. Doesn't start automatically and there is no button I could press..

Do I really have to enter this code manually??

App version 8.1.0

**Comment by mario** [comment]
You should enter your username and password, not the token. Username/password combinations then generates the token automatically.

**Comment by redm123** [comment]
What the purpose of the option to use the token then? Also the security concept of NC seems to encourage to this badly implemented token concept.

**Comment by Ivansss** [comment]
At the moment, the "QR code scan" feature is missing in Talk iOS app.
So if you manually create an app token, you will have to enter it manually.
This feature (QR code scan) will be implemented at some point, so I will leave this issue open to update about the status of this feature.

On the other hand, as @mario said, if you enter your username and password, this will automatically create an app token. This way you don't need to create manually an app token and enter it manually.

**Comment by redm123** [comment]
I see, fair enough. But then I would rather disable the token feature, IMHO. First user impression: It's just confusing otherwise, it looks broken. 
The point of this is to simplify login, by just scanning the QR code, right? Why would I enter that long complicated token string manually? So if QR does not work, it's of no real use and could/should be removed.

**Comment by johkoenig** [comment]
@Ivansss @mario 
When using TOTP as a second factor and the TOTP generator is on the phone you want to set up, then the process becomes very complicated. A user needs to enter his server URL, then username/password, then he has to switch to the Google Authenticator app, remember the code and then he has to switch back to the talk app and enter it (within 30 seconds).  That's not very user friendly. The files app already uses the code, which contains the server URL, username and password/token all in one. So, the user has no need to type anything by hand.
In fact, I would propose to make QR code the default login, and the "normal" way should be listed as "configure manually".
