### ISSUE TITLE
Action icons

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/talk-ios#31]
To unify the experience the Talk app should use the same action icons like the Nextcloud app does.

![ios](https://user-images.githubusercontent.com/1869584/34871348-9b80521e-f78d-11e7-93e7-cac644fd1a70.png)

**Comment by jancborchardt** [comment]
Actually the delete icon and grey/red colors should rather be the same as in the Apple Mail app. See **Adjust action buttons to iOS standard** https://github.com/nextcloud/ios/issues/433
