### ISSUE TITLE
iOS App - Crashes after update to Talk Beta

### ISSUE THREAD

**Issue by FSDirk** [nextcloud/talk-ios#315]
We are Using Beate 9.0.0 Beta 1. Browser based Chat works fine. App crashes immediately after start up on iOS. iOS is up to date. Talk app also up to date. 

Regards, 

Dirk

**Comment by Ivansss** [comment]
Hi Dirk,

Could you share here the crash log you get in the iOS app?
You could also send it to me to `ivan[at]nextcloud[dot]com` if you don't want to post it here.

**Comment by Ivansss** [comment]
Nextcloud Talk iOS v9.0 has been released. This release comes with a bugfix for the issue you had with Talk 9 beta :)
