### ISSUE TITLE
Obey force mute signaling message

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-ios#319]
In Talk 9 moderators have an option to turn of the microphone of participants (see `force-mute` capability).

So if you receive a signaling message with:
```js
	if (message.type === 'control') {
		if (message.payload.action === 'forceMute') {
			if (message.payload.peerId === self.connection.getSessionId()) {
```

Mute the microphone.

**Comment by Ivansss** [comment]
Implemented in https://github.com/nextcloud/talk-ios/pull/290
