### ISSUE TITLE
List view in Contacts view should be same as in Calls/Chats view

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-ios#33]
Currently the avatars are significantly smaller. They should be the same size, and the height of the rows too. :) The name text can be vertically centered.

@Ivansss

**Comment by Ivansss** [comment]
Heights are different because we show different things in each case.
In Calls/Chats we show last time you were in that call at the moment, in the future we will show last chat message.
The height we use in Calls/Chats will leave to much empty space in Contacts.

**Comment by jancborchardt** [comment]
The information doesn't matter. As said the avatars should have the same size. In the Conversations case there will them be 2 rows, for Contacts only 1, vertically centered.

**Comment by Ivansss** [comment]
Already implemented in #36 and added in version 1.1.0.
