### ISSUE TITLE
ringtone while starting a calling

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-ios#333]
On android there is a ringtone when I start a call till it is established, like on the telephone.

**Comment by maprambo** [comment]
I think such a tone would greatly improve user feedback.
I created a sound for dialing and one for ending a call. After that, I realized one could just use the same sound as for Android. Nevertheless, here they are. Use them or drop them.

[sounds.zip](https://github.com/nextcloud/talk-ios/files/5322419/sounds.zip)

**Comment by SystemKeeper** [comment]
Android commit for reference https://github.com/nextcloud/talk-android/commit/642146de02a01de998d5b84ce53d5597d4d17b9e
