### ISSUE TITLE
Show »Settings« as rightmost entry in the bottom tab bar, using profile picture

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-ios#34]
Currently we show it in the top left, but as we will have more profile info and such it should be also in the bottom bar. That simplifies things, and aligns it also to how we do it in Android.

The icon used should also not be the bland »Settings« gear, but the own profile picture (or placeholder), ref https://github.com/nextcloud/talk-android/issues/61

**Comment by Ivansss** [comment]
I think it's a good idea to move settings to the tab bar.
But I think it's better to keep the "Settings gear" icon instead of the profile picture.

**Comment by jancborchardt** [comment]
@Ivansss as talked about on IRC again, we should show the profile picture there (as said above also). Reopening for that :)

**Comment by Ivansss** [comment]
Settings/Profile button will be on the top left of the main screen on the next release (version 3.2).
Also it will show the profile picture of the user.
