### ISSUE TITLE
Group conversation added through invitation link doesn't show up in iOS App

### ISSUE THREAD

**Issue by jameslao** [nextcloud/talk-ios#341]
I'm using Nextcloud 19.0.1 with talk 9.0.2

I sent an invitation link to a user, and on the web page I can see him joining the conversation.

But in the iOS app, that user did not show up in the group conversation. He said that he didn't see the conversation, and I (in the conversation) could not find him. Only after I added him again in the App did he show up and was able to chat.

**Comment by Ivansss** [comment]
Hi @jameslao :)

I think this is more a missunderstanding of the feature than a bug.

If you want to invite permanently a nextcloud user to one conversation, you can add this user as a participant of the conversation.
After that, the user will receive a notification about that, and this user will see that conversation in the conversations list.

The invitation links are meant for users outside of your nextcloud (Guests).
If one of nextcloud instance users follows that link, it will be added temporarely to that conversation. When that users leaves the conversation (closes that browser window or moves to another conversation), it will no longer be part of that conversation. I think this is what you are experiencing.

I hope this helps you to understand better the "Share link" feature and how it works.

**Comment by jameslao** [comment]
Hi @Ivansss, thanks a lot for the explanation. 

I think it might make sense to add users permanently to a conversation through shared links, as that gives users a choice - you can send out the links to a lot of users, but it's up to them to join. Also, since the link is conversation-specific, it is quite confusing for users if they find themselves removed from that conversation after closing the window.

**Comment by nickvergessen** [comment]
This issue is being discussed in the server app, as that is where it needs fixing:
https://github.com/nextcloud/spreed/issues/1763

However there are multiple things to consider, so it's not an easy task and we need to make sure that it somewhat still satisfies everyone.
