### ISSUE TITLE
Calls with participants on mobile devices is unstable

### ISSUE THREAD

**Issue by digitalrevisor** [nextcloud/talk-ios#349]
Hi.

This is an issue we had in the talk repository earlier  but I was encouraged to post it here instead as it seems to be related to the talk mobile apps.

We are running a signaling server and using it with talk. Everything seems to run great in the browser. Both MAC and windows PC doesn't cause any significant problems with the low number of participants we've tested so far in a call.

However, the moment someone tries to connect from a mobile device with the talk app (either on android or IOS), there are several problems taking place.

First, the user connecting from the mobile device into the call doesn't manage to load audio or video. Other participants cannot see them and they cannot see the other participants. Sometimes (but rarely) the mobile device participant can hear or see others, but I haven't found a case of the opposite yet.

Also, when a user is joining the call with a mobile device, other issues sometimes happens. Sometimes this causes other participants on pc/mac who were fine to see eachother before to suddendly lose video or audio of eachother.

I don't know if there is any type of logging that can be provided to make it easier to figure out what the issue is. We are using Nextcloud 19.1 but we've also had this problem on Nextcloud 19 and I think on Nextcloud 18 the problem was there but I can't say for sure since I didn't test it throughly then. We are also running the newest version of Talk published on the app store. Any other details I can provide that would help?

**Comment by AndyXheli** [comment]
Yes I agree with this.

**Comment by vasyugan** [comment]
We just had a group call, where, whenever one of the participants tried to join the ongoing call via IOS talk app by clicking the camera icon he would either

- end up in a new parallel call instead or
- No be seen or heard by the other participants even though he had seemingly joined the call.

I should add that my nextcloud instance has 

1. a stun server
2. a turn server
3. a signalling server (High performance backend)
So this isn't the issue.

**Comment by axheli** [comment]
Do you have a turn server configured!?

**Comment by AndyXheli** [comment]
@Ivansss what do you think about @vasyugan comment! I can agree with him as well I have a turn server configured and we're having the same issues from mobile devices.

**Comment by Ivansss** [comment]
Hi @digitalrevisor and @vasyugan 

Sorry for my late reply in this issue.

How big are the video calls were you are experiencing this issues?
We don't have any restrictions in the code about the number of participants in a call.
But keep in mind that receiving and decoding a large number of video streams could be quite challenging for a mobile device.

**Comment by vasyugan** [comment]
> Hi @digitalrevisor and @vasyugan
> 
> Sorry for my late reply in this issue.
> 
> How big are the video calls were you are experiencing this issues?

Small. Five participants.

> We don't have any restrictions in the code about the number of participants in a call.
> But keep in mind that receiving and decoding a large number of video streams could be quite challenging for a mobile device.

This isn't the problem. (and with the signalling server, which I have set up, it shouldn't anyway) He was able to see and hear the other participants but not vice versa.

The other problem was that when he clicked the camera icon in the chat, instead of joining the ongoing call, a new call was launched.

**Comment by Ivansss** [comment]
> This isn't the problem. (and with the signalling server, which I have set up, it shouldn't anyway) He was able to see and hear the other participants but not vice versa.

Even when you are using the [external signaling server](https://github.com/strukturag/nextcloud-spreed-signaling), in a n-participants call, every participant receives and decodes n-1 audio and video streams.

What version of the signaling server are you using?
What Nextcloud, Talk and Talk iOS versions are you using?

**Comment by vasyugan** [comment]
> > This isn't the problem. (and with the signalling server, which I have set up, it shouldn't anyway) He was able to see and hear the other participants but not vice versa.
> 
> Even when you are using the [external signaling server](https://github.com/strukturag/nextcloud-spreed-signaling), in a n-participants call, every participant receives and decodes n-1 audio and video streams.

Then, what is the high performance backend doing? It is supposed to enable 5-50 participant calls. You are effectively telling me that it cannot, right? And again, this was just a five person call.

Anyway, the problem was not that the client couldn't handle incoming streams. It was the opposite: He could see and hear the others, but the others couldn't see him.
And while it did not work in the ios Nextcloud Talk app, it did work kind of ok in the IOS browser (a version of Safari, I guess)

> 
> What version of the signaling server are you using?

Pre-packaged debs from https://gitlab.com/packaging/nextcloud-spreed-signaling/, currently at version 202009181915-76f327b

> What Nextcloud, Talk 

 spreed: 10.0.0

> and Talk iOS versions are you using?

That I don't know as it is not my device. I can asked but since I guess that ios apps update automatically, I would guess that they track the latest version.

**Comment by AndyXheli** [comment]
I just this issue today on the morning. 

I made a call via Web and some users coming from IOS app did not come throw im using the stun.nextcloud.com and i have my own turn server setup. 

But the mobile is unstable.

**Comment by Ivansss** [comment]
> > > This isn't the problem. (and with the signalling server, which I have set up, it shouldn't anyway) He was able to see and hear the other participants but not vice versa.
> >
> > Even when you are using the [external signaling server](https://github.com/strukturag/nextcloud-spreed-signaling), in a n-participants call, every participant receives and decodes n-1 audio and video streams.
>
> Then, what is the high performance backend doing? It is supposed to enable 5-50 participant calls. You are effectively telling me that it cannot, right? And again, this was just a five person call.

Sorry for the confusion. That was definitely not what I was trying to say.

I was just trying to explain you that even with the high permormance backend, every client still receives (n-1) audio and video streams. So in large calls (not in a 5 participant call) it could be challenging for a mobile device to decode all these video streams.

I just skipped the part saying that this should not be an issue in a 5 participant call and just went directly to ask you questions about your setup to try to find out what could be causing these problems in your setup.

Is your issue reproducible? Could you check the signaling server logs when this happens and see if there are some errors there?

**Comment by AndyXheli** [comment]
@Ivansss i dont think its just his setup though. Based on my experience the mobile is a hit or miss sometimes participants  will connect and sometimes they are there but can see or hear anyone. I has a call yesterday and someone joined from an IOS device and i didn't see them on my computer via web then i left the meeting and rejoined and then it worked some goes for the users. i don't know but some of my user are so frustrated they stopped using it. I defiantly  think that there has to be a resolution here  @vasyugan what do you think same issue as me ?

**Comment by vasyugan** [comment]
> > > > This isn't the problem. (and with the signalling server, which I have set up, it shouldn't anyway) He was able to see and hear the other participants but not vice versa.
> > > 
> > > 
> > > Even when you are using the [external signaling server](https://github.com/strukturag/nextcloud-spreed-signaling), in a n-participants call, every participant receives and decodes n-1 audio and video streams.
> > 
> > 
> > Then, what is the high performance backend doing? It is supposed to enable 5-50 participant calls. You are effectively telling me that it cannot, right? And again, this was just a five person call.
> 
> Sorry for the confusion. That was definitely not what I was trying to say.
> 
> I was just trying to explain you that even with the high permormance backend, every client still receives (n-1) audio and video streams. So in large calls (not in a 5 participant call) it could be challenging for a mobile device to decode all these video streams.
> 
> I just skipped the part saying that this should not be an issue in a 5 participant call and just went directly to ask you questions about your setup to try to find out what could be causing these problems in your setup.
> 
> Is your issue reproducible? Could you check the signaling server logs when this happens and see if there are some errors there?

We have group calls with this very composition every few weeks. So I have to wait. Of course, using my colleague as a guinea pig also feels a bit unpleasant, so I'll have to see whether I can arrange something else.

**Comment by vasyugan** [comment]
> @Ivansss i dont think its just his setup though. Based on my experience the mobile is a hit or miss sometimes participants will connect and sometimes they are there but can see or hear anyone. I has a call yesterday and someone joined from an IOS device and i didn't see them on my computer via web then i left the meeting and rejoined and then it worked some goes for the users. i don't know but some of my user are so frustrated they stopped using it. I defiantly think that there has to be a resolution here @vasyugan what do you think same issue as me ?

Sounds simillar, yes. And yes, the social problem is that once they have experienced these difficulties, most users will just go back to Zoom and stay with it, and that's what I would like to avoid. The most important part is reliability of the service. And while nextcloud talk seems to work fine on the desktop, the mobile apps still seem to cause a lot of issues.

**Comment by axheli** [comment]
@Ivansss @vasyugan I think this is more related to IOS talk app ive been doing some testing and works alot smoother on android.

**Comment by digitalrevisor** [comment]
Its also bugg on android app.

**Comment by AndyXheli** [comment]
Yes, I agree it is a bug on android as well.

**Comment by Ivansss** [comment]
> We just had a group call, where, whenever one of the participants tried to join the ongoing call via IOS talk app by clicking the camera icon he would either
> - end up in a new parallel call instead or
> - No be seen or heard by the other participants even though he had seemingly joined the call.

@vasyugan There are some bugfixes https://github.com/nextcloud/talk-ios/pull/399 included in the latest release 10.1 that could solve the issues you described.
