### ISSUE TITLE
Images are sent in the wrong orientation

### ISSUE THREAD

**Issue by maprambo** [nextcloud/talk-ios#362]
1. Take a photo in landscape orientation
2. Open a chat in Nextcloud Talk
3. Pick the image via the in-chat image picker
4. Send it

Expected behaviour: The image is sent as seen in the photo gallery and image picker. It is in landscape orientation.
Actual behaviour: The image is turned left or right. Neck gets stretched.

Versions:
Talk iOS app: 10.0.0
iOS: 14.0.1
Talk server app: 9.0.4
Nextcloud Hub: 19.0.3

**Comment by jasondaigo** [comment]
Isnt it just a 50x50 px thumbnail with a link to an external app or mobile browser? There are no uploads yet or am I wrong?

**Comment by Ivansss** [comment]
@jasonbayton The file upload feature has been implemented in Talk 10 :)
@maprambo Thanks for reporting the issue ;)
