### ISSUE TITLE
Talk app immediately closes upon opening ios 10.3.2

### ISSUE THREAD

**Issue by Dantali0n** [nextcloud/talk-ios#366]
# Expected behaviour

App opens and does not close automatically. As the description of Nextcloud talk it's compatibility says only IOS 10 or higher is required. See https://apps.apple.com/us/app/nextcloud-talk/id1296825574 **Compatibility: Requires iOS 10.0 or later. Compatible with iPhone, iPad, and iPod touch.**

# Actual behaviour

Splash screen shows briefly app closes automatically.

# Steps to reproduce

1. Open app
2. App crashes

# Reasoning or why should it be changed/implemented?

Can't use app if it crashes immediately.

# iOS version

10.3.2 (14F89)

# App version

10.0.0

# Server configuration

I highly doubt these are at all relevant but sure.

**Operating system: Ubuntu 18.04**

**Web server: Apache 2.4.?**

**Database: Mariadb**

**PHP version: 7.3**

**Nextcloud version: 19.0.3**

**Comment by Ivansss** [comment]
Hi @Dantali0n,

Does this happen in a fresh installation of the app? Or you just updated to Talk v10.0 and it's not working any more?

**Comment by Dantali0n** [comment]
> Hi @Dantali0n,
> 
> Does this happen in a fresh installation of the app? Or you just updated to Talk v10.0 and it's not working any more?

This was upgrading from an existing installation, thank you for the quick reply.

**Comment by Ivansss** [comment]
> This was upgrading from an existing installation, thank you for the quick reply.

Interesting 🤔 Did you already try to uninstall the app and install it again?
I don't have any iOS 10 device here at the moment.

**Comment by Dantali0n** [comment]
I have reinstalled the app and the behavior persists.

**Comment by Ivansss** [comment]
Ok. Do you have a mac?
Could you connect your iOS Device to your mac and open the "Console" app in your mac?
Then select your device on the left side bar and search for VideoCalls [PROCESS] 
<img width="341" alt="Screenshot 2020-10-08 at 13 15 22" src="https://user-images.githubusercontent.com/4638605/95451801-97070300-0968-11eb-9ed1-85095aa834ea.png">
After that you can launch the Talk app in your iOS Device and check if there are some errors in the logs.
You can also paste them here if you want.

**Comment by Dantali0n** [comment]
> Ok. Do you have a mac?
> Could you connect your iOS Device to your mac and open the "Console" app in your mac?
> Then select your device on the left side bar and search for VideoCalls [PROCESS]
> <img alt="Screenshot 2020-10-08 at 13 15 22" width="341" src="https://user-images.githubusercontent.com/4638605/95451801-97070300-0968-11eb-9ed1-85095aa834ea.png">
> After that you can launch the Talk app in your iOS Device and check if there are some errors in the logs.
> You can also paste them here if you want.

I do not own any devices capable of running MacOS, sorry. I could make an attempt at setting up a MacOS VM with USB passthrough if that is desired?

**Comment by Ivansss** [comment]
I might have access to one iOS device with iOS 10 next week. I could then debug what's causing this issue.
Thanks for reporting the issue!
Sorry for not being able to solve your issue. I guess you can't upgrade your iOS device to a newer iOS version right?

**Comment by Dantali0n** [comment]
> I might have access to one iOS device with iOS 10 next week. I could then debug what's causing this issue.
> Thanks for reporting the issue!
> Sorry for not being able to solve your issue. I guess you can't upgrade your iOS device to a newer iOS version right?

That is correct I am unable to upgrade to a higher IOS verison, honestly it is becoming pretty EOL as more and more apps require at least IOS 11 or higher.

**Comment by Ivansss** [comment]
Yeah. We were also thinking about setting iOS 11 as the required minimum version for this release.
Let me try to debug this problem in an iOS 10 device and I will update this issue.

**Comment by SystemKeeper** [comment]
You should be able to retrieve the crash log even without mac os, @Dantali0n. See https://stackoverflow.com/questions/24400414/how-to-locate-app-crash-logs-in-iphone-ipad

**Comment by Dantali0n** [comment]
Behold logs: http://paste.ubuntu.com/p/mBrszCQZVP/

_Apple really made this as impossible as possible (can't send via email manually have to copy text not even a select all option jeeesh)._

**Comment by Ivansss** [comment]
@Dantali0n Do you have an iPhone 5s?

**Comment by Dantali0n** [comment]
> @Dantali0n Do you have an iPhone 5s?

Yes this is correct.

**Comment by Ivansss** [comment]
Then you should be able to update to iOS 12, right? 🤔

**Comment by Ivansss** [comment]
It doesn't mean that this issue will be solved by updating your iOS version.
But I was just wondering why you stayed in iOS 10.

**Comment by Dantali0n** [comment]
> Then you should be able to update to iOS 12, right? thinking

I did not even know it could upgrade beyond 10. Good to know I guess. If I want to upgrade I will have to evaluate, I remember Apple changed the behavior of the WiFi and Bluetooth buttons in the quick menu to not disable the feature but simply disconnect from the current connection. If this is the case with 12 than I rather not switch.

**Comment by Ivansss** [comment]
Yeah, I think it's better if you evaluate if it makes sense for you to update to a newer iOS version.
As I said in my last post, this issue might not be fixed just by updating to a newer iOS version.
I need some more time to investigate it :)

**Comment by Dantali0n** [comment]
Upgrading to ios 12 has resolved the issue :), I now will forever have to endure the pain of opening settings to fully disable Bluetooth and WiFi :(

**Comment by Ivansss** [comment]
Glad to hear that you can use the app now :)

> I now will forever have to endure the pain of opening settings to fully disable Bluetooth and WiFi :(

Sorry for that 😅

**Comment by Ivansss** [comment]
This issue has been fixed in Talk iOS v10.0.1.

**Comment by DeeeeLAN** [comment]
What was the fix?

**Comment by Dantali0n** [comment]
> What was the fix?

https://github.com/nextcloud/talk-ios/commit/fcec8d87b1a53529dc7022cfc38a21bb0b64f787

**Comment by Ivansss** [comment]
> https://github.com/nextcloud/talk-ios/commit/fcec8d87b1a53529dc7022cfc38a21bb0b64f787

That was the fix yes :)
