### ISSUE TITLE
Talk app connection issues.

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/talk-ios#369]
When someone calls you from a computer and when trying to join the invite via Nextcloud talk app or in the mobile web browser like sefari or Chrome on iOS it doesn't connect or it doesn't not show a picture\voice or it takes forever but pc to pc works with no issues it's like a hit or miss and the mobile app I've tried it from different servers and same issue so it's not isolated just on my server. 

Someone else reported this issue as well #349

**Comment by AndyXheli** [comment]
I also uploaded a video explaining the issue. I hope this helps.  


[Video.zip](https://github.com/nextcloud/talk-ios/files/5366999/Video.zip)

**Comment by Ivansss** [comment]
Hi @axheli 
Do you have a TURN server configured in your setup?
https://nextcloud-talk.readthedocs.io/en/latest/TURN/

**Comment by AndyXheli** [comment]
> Hi @axheli 
> 
> Do you have a TURN server configured in your setup?
> 
> https://nextcloud-talk.readthedocs.io/en/latest/TURN/

Hello. No I don't should I be ?

**Comment by Ivansss** [comment]
Yes. That should be the cause of your issues with mobile devices.
You probably didn't have any issues when calling from on pc to another because they probably were in the same local network (in that case a TURN server is not needed).

**Comment by AndyXheli** [comment]
Okay i will figure out how to set that up then. But PC to PC was not on the same local network One pc was from the USA and other was from albania and it worked just fine but only mobile units are have the issue.

**Comment by AndyXheli** [comment]
Also, do I install the cotrun on the same server as nextcloud or a different server? how should i go about this?

**Comment by Ivansss** [comment]
> But PC to PC was not on the same local network One pc was from the USA and other was from albania and it worked just fine but only mobile units are have the issue.

I see. Then it can be that with the STUN server that is pre-configured with Talk it was enough to create a connection between both PCs. But in some other scenarios the TURN server will be needed. So it is highly recommended to setup one.

> Also, do I install the cotrun on the same server as nextcloud or a different server? how should i go about this?

You can install it on the same server as Nexcloud or in a different one.

**Comment by AndyXheli** [comment]
Perfect thank you sir! 💯

**Comment by axheli** [comment]
@Ivansss so i just setup the turn server and its still having the same issue.

**Comment by axheli** [comment]
looks like that did it.

**Comment by AndyXheli** [comment]
Duplicate #349
