### ISSUE TITLE
Camera or video?

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-ios#375]
Shouldn't there be a camera instead of a video?
`Do you want to enable your video?`

https://github.com/nextcloud/talk-ios/blob/c4166cceadc1c825c7d75e5760f7149c13514efc/NextcloudTalk/CallViewController.m#L742

**Comment by Ivansss** [comment]
I think "camera" would make more sense from a user perspective.
Do you want to open a PR with the change? :)

**Comment by Valdnet** [comment]
@Ivansss  PR: #376. Please approval. Thanks 😉.
