### ISSUE TITLE
Context needed for string "on"

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/talk-ios#383]
https://github.com/nextcloud/talk-ios/blob/00a65639ef80e30a17d5c971576d01a7d1411574/NextcloudTalk/en.lproj/Localizable.strings#L481

Switching something on and off?
Or "on the table"?

**Comment by rakekniven** [comment]
@Ivansss You maybe?

**Comment by Ivansss** [comment]
Hi @rakekniven :)
Thanks for opening the issue.
This string is for a switch On/Off.
I was thinking about adding some comments to localizable strings but I'm not sure if those comments are visible in transifex.
Do you know if comments are visible in transifex?

**Comment by rakekniven** [comment]
> Do you know if comments are visible in transifex?

It depends on the programming language. For php and js it works. For vue files it doesn't (has something to do with the compressed stuff). @MorrisJobke may know some details.

**Comment by rakekniven** [comment]
Please add a comment related to this issue and I will check.

**Comment by Ivansss** [comment]
> Please add a comment related to this issue and I will check.

Where should I add a comment?

**Comment by rakekniven** [comment]
> I was thinking about adding some comments to localizable strings

At the source code 😄

**Comment by MorrisJobke** [comment]
> > Please add a comment related to this issue and I will check.
> 
> Where should I add a comment?

Typically on the line above.

In PHP this looks like this:

```php
// TRANSLATORS this is the language name for the language switcher in the personal settings and should be the localized version
$potentialName = (string) $l->t('__language_name__');
```

The `TRANSLATORS` here is the keyword for `gettext` to extract it as metadata.

**Comment by Ivansss** [comment]
I have added 2 comments in https://github.com/nextcloud/talk-ios/commit/5fd6499a0aaab3ce29cb593196051a1e3e82bc71

This is the file that is uploaded to transifex. So it will contain the comments now. https://github.com/nextcloud/talk-ios/blob/5fd6499a0aaab3ce29cb593196051a1e3e82bc71/NextcloudTalk/en.lproj/Localizable.strings#L480-L481

Will these comments be visible in transifex? I can't find the place where this kind of comments are displayed :S

**Comment by rakekniven** [comment]
<img width="1264" alt="Bildschirmfoto 2020-10-21 um 21 02 56" src="https://user-images.githubusercontent.com/2069590/96770574-e1fd2d80-13e0-11eb-92f0-ef51588ca229.png">

Will check tomorrow

**Comment by MorrisJobke** [comment]
@rakekniven Needs to be synced first. Let me trigger that (otherwise it runs only once a day)

**Comment by rakekniven** [comment]
@MorrisJobke I know. Just want to show Ivan the element where to look for.

**Comment by MorrisJobke** [comment]
Somehow didn't worked. I need to look into why it is not properly extracted?

**Comment by Ivansss** [comment]
> Just want to show Ivan the element where to look for.

Thanks @rakekniven :) I wasn't able to see it 😅

<img width="302" alt="Screenshot 2020-10-22 at 09 58 36" src="https://user-images.githubusercontent.com/4638605/96842419-4a81f400-144d-11eb-9abe-d3a3a92651c4.png">

So it looks like it grabs the whole comment. Should I use the `TRANSLATORS` keyword then?

**Comment by rakekniven** [comment]
Yes, please.

**Comment by MorrisJobke** [comment]
> So it looks like it grabs the whole comment. Should I use the `TRANSLATORS` keyword then?

Ah yes, because the second argument is just for that purpose. In PHP this keyword is actually needed. So yes, you can remove the keyword and then this is solved. 🚀
