### ISSUE TITLE
Enable camera automatically

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/talk-ios#387]
Currently if someone makes a call and you answer vis iOS talk app it always joins just audio then you have to hit the video button to enable to camera then at this joins and re-join the meeting that is very frustrating for some users is there a way to have it automatically enable to camera when you answer the call

**Comment by AndyXheli** [comment]
Also wanted to comment just like when someone facetimes you if someone calls if you click on the video it should automatic enable it at first when joining the conversation current it joins as audio then when clicking the video button it leaves the call and rejoins via video. It would be nice for it to be more smooth and seamless.

**Comment by AndyXheli** [comment]
@Ivansss What do you think about this?

**Comment by Ivansss** [comment]
Not possible at the moment since the server doesn't differenciate between a voice or a video call when sending a notification to mobile apps.
We will keep the default as it is (voice call) in mobiles until the server sends different notifications for voice or video calls.

**Comment by AndyXheli** [comment]
Understood! Thank you for letting me know! How do you want me to go about this? Keep ticket open?

**Comment by Ivansss** [comment]
Let's keep it open so I can post updates about this feature here  ;)

**Comment by Ivansss** [comment]
Hi @axheli 
In the next version (Talk iOS v11) incoming calls will differentiate between audio or video calls. #502 
Video is default by default when answering a video call, but the user will join the call as a video call (just with its own video disabled)
If the user then wants to enable its own camera, the user just need to press the video button and the video will be activated and send to the other peers in the call without any re-connection.
I'm closing this issue now :)

**Comment by AndyXheli** [comment]
@Ivansss Wooohooooo super happy!!!! Cant wait to test it. Thank you!
