### ISSUE TITLE
Crash in -[NCCallController getPeerConnectionWrapperForSessionId:ofType:] when joining call

### ISSUE THREAD

**Issue by ghost** [nextcloud/talk-ios#391]
The app (version 10.0.1 from the App Store as well as current version from git) crashes every time when I want to join an ongoing call or (when the call is started in the app) as soon as anybody else joins the call.

[NCCallController.m line  433](https://github.com/nextcloud/talk-ios/blob/c4166cceadc1c825c7d75e5760f7149c13514efc/NextcloudTalk/NCCallController.m#L433)

`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSDictionaryM setObject:forKey:]: key cannot be nil'`

[VideoCalls-2020-10-31-063655.ips.txt](https://github.com/nextcloud/talk-ios/files/5468577/VideoCalls-2020-10-31-063655.ips.txt)

**Comment by Ivansss** [comment]
Hi @tobiasmboelz 
What Nextcloud sever and Talk versions are you using?

**Comment by ghost** [comment]
Nextcloud 20.0.1, Nextcloud Talk 10.0.1, Signaling Server dbcbad8b997c48e8a37fbd6d7ebdc62275e780a2

**Comment by Ivansss** [comment]
Could you provide me with a test account in your instance? I can't reproduce your issue here.
You could send me an email to ivan [at] nextcloud [dot] com.

**Comment by Ivansss** [comment]
The app was crashing because Talk was configured with the external signaling server without the mcu/janus component.
https://github.com/strukturag/nextcloud-spreed-signaling#setup-of-janus

The issue has been fixed in #402 and the fix will be included in the next release.
