### ISSUE TITLE
Unexpected type: mute/unmute

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/talk-ios#395]
When using external signaling I'm seeing the following messages logged:

```
2020-10-31 21:59:14.009074+0100 VideoCalls[16317:4002636] External signaling message received: {
    data =     {
        payload =         {
            name = audio;
        };
        prefix = webkit;
        roomType = video;
        sid = 1604177938086;
        to = "...";
        type = mute;
    };
    sender =     {
        sessionid = ...;
        type = session;
        userid = "marcel.mueller";
    };
}
2020-10-31 21:59:14.009166+0100 VideoCalls[16317:4002636] Unexpected type: mute

(...)

2020-10-31 22:02:42.675173+0100 VideoCalls[16317:4004755] External signaling message received: {
    data =     {
        payload =         {
            name = video;
        };
        prefix = webkit;
        roomType = video;
        sid = 1604178146194;
        to = "...";
        type = unmute;
    };
    sender =     {
        sessionid = ...;
        type = session;
        userid = "marcel.mueller";
    };
}
2020-10-31 22:02:42.675308+0100 VideoCalls[16317:4004755] Unexpected type: unmute
```

Those do not effect muting or unmuting. Also the message "You have been muted by a moderator" is shown, so I guess it's safe to ignore those messages for now. In case we want to show the mute/unmute state of other participants, this message should be processed.

**Comment by Ivansss** [comment]
This is because we are moving away from using datachannels to using signaling messages only. (Since there are some browsers like Edge that don't support datachannels).
At the moment we just don't handle those signaling messages and that's the reason of those logs.

I'm going to close this since it's not a real issue :)
