### ISSUE TITLE
Icon of unmute button is not centered

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/talk-ios#405]
Ok.. total nitpicking here:

![image](https://user-images.githubusercontent.com/1580193/98486438-8d99e080-221d-11eb-893e-6fccda3c7f1c.png)

The file `audio-off` (along with its `@2x` / `@3x` counterparts) is not centered itself, so it's not a problem of any code.

**Comment by Ivansss** [comment]
Thanks for reporting it :)
