### ISSUE TITLE
Click on a file should show them in the nextcloud app

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-ios#408]
Currently they will open in the mobile browser

**Comment by SystemKeeper** [comment]
Shared files will only open in mobile browser if the Nextcloud-App is not installed. Which versions of Talk-App and Nextcloud-App are you using?

**Comment by jakobroehrl** [comment]
Tested again and this is working, sorry. 
Maybe it would be better to open the file directly not only marking it. 
In a big folder it's hard to find and I think the user whats to see it big in most cases
