### ISSUE TITLE
l10n: New resource at Transifex with 3 strings of info.plist

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/talk-ios#413]
Hello,

since yesterday there is a new resource available at Transifex containing three strings.

Did a search and found them at:

https://github.com/nextcloud/talk-ios/blob/7a8469aefbbcd9f8f0eb1ff6e33d42073071d00f/NextcloudTalk/en.lproj/InfoPlist.strings

Please include them in file "Localizable.strings":

https://github.com/nextcloud/talk-ios/blob/7a8469aefbbcd9f8f0eb1ff6e33d42073071d00f/NextcloudTalk/en.lproj/Localizable.strings

We want to have only one resource at Transifex for each project.

**Comment by rakekniven** [comment]
Hello @Ivansss ,

just seen your commit from yesterday:
https://github.com/nextcloud/talk-ios/commit/3607c6179e884124541a607f3ca03fe2bd173aa7

We need to find another solution for integration.

**Comment by Ivansss** [comment]
Hi @rakekniven :)

Sorry for the late reply!
I tried to put all strings in "Localizable.strings" but it seems that it's not possible.
As Apple says in their documentation, to localize values in Info.plist, you should create a InfoPlist.strings file.
https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/AboutInformationPropertyListFiles.html#//apple_ref/doc/uid/TP40009254-102276

I think there is not much I can do here :S
Do you have any idea?

**Comment by rakekniven** [comment]
How is @marinofaggiana doing this for the ios app?

**Comment by Ivansss** [comment]
I think the Info.plist strings are not localized in the Nextcloud iOS app. :/

**Comment by rakekniven** [comment]
> it's corrected

You mean "it is correct"?

What is this InfoPlist.strings for?

**Comment by SystemKeeper** [comment]
> What is this InfoPlist.strings for?

It's used when an app requests permissions, for example for using the camera. This is required in order to allow such a request, see [here](https://developer.apple.com/documentation/bundleresources/information_property_list/nscamerausagedescription)

**Comment by rakekniven** [comment]
Thanks for the explanation. @marinofaggiana Wouldn't this be something useful for your app as well?

**Comment by rakekniven** [comment]
> can't be mixed in other files

Ok, but can it be merged somehow to only have one resource at Transifex?
