### ISSUE TITLE
Switch accounts when sharing from SharingExtension

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/talk-ios#423]
Currently when you share something through the SharingExtension (image from the photos app for example) you can't change accounts, in case there're multiple configured. The current active account is always used.

In case there is more than one account we should provide a way to switch accounts.

**Comment by nickvergessen** [comment]
1. Have 2 accounts set up
2. Use account A in the talk app
3. Go to your photos app
4. Try to share a photo to a conversation of account B

<img width="975" alt="2021-04-19 09-30-46-1" src="https://user-images.githubusercontent.com/213943/115198311-32381c80-a0f2-11eb-9a1a-a26db4909523.png">

There is no way to switch to another account.
