### ISSUE TITLE
The app freezes my iPhone

### ISSUE THREAD

**Issue by ldesgrange** [nextcloud/talk-ios#424]
Hi,

I updated Talk to version 10.1.0 on iPhone 6 with iOS 12.4.9. If I launch the application, I can see my messages as normal, then I leave the app, when I want to launch it again, the icon goes darker (normal) but that's it, nothing happens on my phone anymore, I have to hard-reboot it (or wait for the iPhone do to that itself).

If I start my iPhone and does nothing with it (not starting any app), I can hear notification when people are sending me messages on Talk, but after a while the iPhone crashes also, I can't even turn on the screen need to hard-reboot.

I assumed it's Talk related, but I can't be 100% sure, the problem starting happening today after updating Nextcloud App and Nextcloud Talk App.

**Comment by Ivansss** [comment]
Hi @ldesgrange 

Interesting 🤔 We didn't introduce drastic changes in this 10.1 version.
Did you have already 10.0 or 10.0.1 installed before? Or did you you updated from a 9.x version?

Have you tried uninstalling the Talk iOS app and see how your iPhone behaves? (Just to check if these behaviours only occurs when the Talk iOS app is installed)

I would do the following tests:
- Uninstall the app and check how your iPhone behaves.
- Install the app but to not add any account and check how your iPhone behaves.
- Set up your account and check how your iPhone behaves.

**Comment by ldesgrange** [comment]
I do my updates very regularly so I think I was already on version 10.x. I'll try your suggestions and keep you updated.

**Comment by ldesgrange** [comment]
Uninstall, used my phone otherwise normally for about 2 hours, no crash.
Installed Nextcloud Talk, start it, it shows me the screen to add an account, didn't set my account up, back to home screen, touch Nextcloud Talk icon again, freeze.

**Comment by SystemKeeper** [comment]
When your phone is in the „freeze-state“ (touched talk icon which turns dark) and you let it sit there for a few minutes, does it recover then?

Can you access the task switcher while in that state and can you close the Talk app from there?

Can you please have a look if a crash report is generated? Either for NextCloud Talk or at the same time as the freeze happened? https://www.macobserver.com/tips/quick-tip/how-to-find-app-crash-reports-iphone-ipad/

**Comment by ldesgrange** [comment]
Yes, the iPhone recovers after a while: dark screen with spinning wheel for a second then back to normal spring board.

When frozen I can't access the task switcher, whatever I do nothing happen, only hard reboot (home+power for a few seconds does something) or wait for it to recover by itself.

I'll check if I can get the crash report.

**Comment by ldesgrange** [comment]
@SystemKeeper got a stacks+backboard file generated when iOS recovers from the freeze. How do I share that file to you?

**Comment by SystemKeeper** [comment]
@ldesgrange If you want, you can post it here. Alternativly you can send it directly to `ivan [at] nextcloud [dot] com` - he knows that you might send a report. Thank you!

**Comment by SystemKeeper** [comment]
Thanks for the report @ldesgrange ! We looked into this, but we can't figure something out, which is related to talk... Is there anything special about your device? I've found a few reports about jailbroken devices, is your device jailbroken? As you did not login after re-install, we can rule out anything special about your nc-instance.

**Comment by ldesgrange** [comment]
My device is not jailbroken, it's just getting old ;-), I don't think there's anything special about it otherwise.

iOS 12 got it's last and final update a couple of weeks ago and won't be supported by Apple anymore. So don't bother looking into this issue anymore if I'm the only one to have it.

**Comment by ldesgrange** [comment]
In the Talk App, I logged in with my nc instance and after a while I got to 2 Nextcloud Talk app crash reports, sending them to you.

**Comment by Ivansss** [comment]
After checking your crash reports it seems that you are hitting a rare Realm issue that is still open :/
https://github.com/realm/realm-cocoa/issues/6763
Let's see if they fix it in one of the next releases and after we update the Realm library it solves your problems.

**Comment by Ivansss** [comment]
We updated the Realm library in Talk iOS version 10.1.2.
This version is already in the App Store.
Would you like to give a try and see if the issue has been solved? :)

**Comment by ldesgrange** [comment]
No crash so far, sounds good to me 👍.

**Comment by Ivansss** [comment]
Thanks for your crash reports and all the info you provided us.
It really helped us to identify the issue :)
