### ISSUE TITLE
Ringtones keeps ringing

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/talk-ios#433]
Hello, is there a way to have the app detect once you join the call from a different devices. So what i can see happing is if someone calls me all of my phones will ring but if I answer it from my computer or one of the phones the the other phones will still keep ringing then eventually it will stop . Is there a way to have the app detect that you've answered the call and stop ringing?

**Comment by Ivansss** [comment]
Thanks for bringing this up @axheli. There is a way to detect if the call has been picked in another device, but it hasn't been implemented yet.
So I will use this issue to update about the progress on this feature.

**Comment by AndyXheli** [comment]
@Ivansss You're welcome. Happy to help so far loving the product thanks for all you do.
