### ISSUE TITLE
Handle preferredContentSizeCategory

### ISSUE THREAD

**Issue by Ivansss** [nextcloud/talk-ios#435]
The font size should be calculated using preferredContentSizeCategory in custom views.

**Comment by SystemKeeper** [comment]
https://github.com/nextcloud/talk-ios/blob/e6d9504d780e3277c32b0478fcd92c492f7a9a88/NextcloudTalk/ChatMessageTableViewCell.m#L260-L268

There's already some older work on this. Didn't this work properly? Move `defaultFontSize` to superclass, change hardcoded values in `NCChatMessage` and maybe do sth. like `SLKPointSizeDifferenceForCategory` in `NCUserInterfaceController`?

**Comment by bmcgonag** [comment]
I would love to see this done. I have low vision, so reading the chat messages is difficult.  Other than that the app is great.

**Comment by bmcgonag** [comment]
Any chance of bumping this up the todo list?

**Comment by JochenKanta** [comment]
In my ecosystem a lot of users are requesting this, I would love to see this done.
