### ISSUE TITLE
Anyone else missing Phone and Camera Icons from conversations?

### ISSUE THREAD

**Issue by Minnietheandroid** [nextcloud/talk-ios#439]
Did an ios-Talk upgrade recently and the phone and Camera icons are missing from the top bar in conversations.
Can click the blank space and it starts a call, same with video chat.

10.1.2 on iPhone 6

**Comment by Ivansss** [comment]
What iOS version are you using?

**Comment by Minnietheandroid** [comment]
iPhone 6 - ios 10.3.3, iPad4 - ios 10.3.3 and iPhone 5 -10.3.4. Same thing on all after updating the app.

**Comment by SystemKeeper** [comment]
Thanks for the report - was able to reproduce this on 10.3.1.

**Comment by Minnietheandroid** [comment]
Thank you. Love the app :)
