### ISSUE TITLE
NextCloud Talk App [iOS] Connection issues

### ISSUE THREAD

**Issue by DarkToaster69** [nextcloud/talk-ios#448]
Hello,
I have a problem with the NextCloud Talk app on iOS.
When I am logged in I do not see any messages and no contacts.
Another user from the same web server is using NextCloud Talk on an Android device and can use NextCloud Talk App normally.

iOS version: 14.3
App Version: 10.1.2
NextCloud version: 20.0.4

LG SleepingToaster

**Comment by Ivansss** [comment]
Hi @SleepingToaster 
After you log in do you see your conversations? And then when you enter there are no messages?
Is this issue reproducible with other users (from the same server) using the Talk iOS app?

**Comment by DarkToaster69** [comment]
No, I don't see any conversations. Not even with another account on another iPhone

**Comment by Ivansss** [comment]
Okay...
Could you create a test account in your server and send it to me (ivan [at] nextcloud [dot] com)?
Do you see anything in the Nextcloud log file?

**Comment by DarkToaster69** [comment]
I have sent you the email. And I see a lot of permission errors

**Comment by Shen** [comment]
I've got the same problem. Maybe this log-entry helps?
`{"reqId":"UeM391mVC1GVRLoYmbBV","level":3,"time":"2021-01-14T20:01:35+00:00","remoteAddr":"[MYIPADDRESS]","user":"john.doe","app":"no app in context","method":"GET","url":"/NEXTCLOUDPATH/ocs/v2.php/apps/spreed/api/v1/room?noStatusUpdate=0","message":{"Exception":"Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException","Message":"An exception occurred while executing 'UPDATE `oc_talk_participants` SET `session_id` = ?, `in_call` = ? WHERE (`user_id` = ?) AND (`room_id` = ?) AND (`participant_type` <> ?) AND (`session_id` = ?)' with params [\"0\", 0, \"john.doe\", 1066, 5, \"EOED8Ji5MoxQZ3MtirpKRHYmunk4nBK6VsrQsuMZxQVJpnMSHWqWyZswgw8SDdMcPbs5JONBMM0hoxu2ln8PaLUCAcBUAgWNSr3BbsR68S1kSHr5h6KKGr6ve+Xuzl4CW\\/y8AMAVIG2Iss3QoF21zhvAh\\/xhb9dMUPCu3kNyJTvAhgPrVOJSI+uaPY8Vak\\/B2AIFQvDnX\\/MjBHTMtWyb2Tki0B8PJ\\/UZ5D\\/CNsxS8l0oa61nGL+KG4hN8nwiTPJ\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1066-john.doe-0' for key 'tp_ident'","Code":0,"Trace":[{"file":"/WEBROOT/NEXTCLOUDPATH/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php","line":169,"function":"convertException","class":"Doctrine\\DBAL\\Driver\\AbstractMySQLDriver","type":"->","args":["An exception occurred while executing 'UPDATE `oc_talk_participants` SET `session_id` = ?, `in_call` = ? WHERE (`user_id` = ?) AND (`room_id` = ?) AND (`participant_type` <> ?) AND (`session_id` = ?)' with params [\"0\", 0, \"john.doe\", 1066, 5, \"EOED8Ji5MoxQZ3MtirpKRHYmunk4nBK6VsrQsuMZxQVJpnMSHWqWyZswgw8SDdMcPbs5JONBMM0hoxu2ln8PaLUCAcBUAgWNSr3BbsR68S1kSHr5h6KKGr6ve+Xuzl4CW\\/y8AMAVIG2Iss3QoF21zhvAh\\/xhb9dMUPCu3kNyJTvAhgPrVOJSI+uaPY8Vak\\/B2AIFQvDnX\\/MjBHTMtWyb2Tki0B8PJ\\/UZ5D\\/CNsxS8l0oa61nGL+KG4hN8nwiTPJ\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1066-john.doe-0' for key 'tp_ident'",{"errorInfo":["23000",1062,"Duplicate entry '1066-john.doe-0' for key 'tp_ident'"],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"}]},{"file":"/WEBROOT/NEXTCLOUDPATH/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php","line":149,"function":"wrapException","class":"Doctrine\\DBAL\\DBALException","type":"::","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDOMySql\\Driver"},{"errorInfo":["23000",1062,"Duplicate entry '1066-john.doe-0' for key 'tp_ident'"],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"},"An exception occurred while executing 'UPDATE `oc_talk_participants` SET `session_id` = ?, `in_call` = ? WHERE (`user_id` = ?) AND (`room_id` = ?) AND (`participant_type` <> ?) AND (`session_id` = ?)' with params [\"0\", 0, \"john.doe\", 1066, 5, \"EOED8Ji5MoxQZ3MtirpKRHYmunk4nBK6VsrQsuMZxQVJpnMSHWqWyZswgw8SDdMcPbs5JONBMM0hoxu2ln8PaLUCAcBUAgWNSr3BbsR68S1kSHr5h6KKGr6ve+Xuzl4CW\\/y8AMAVIG2Iss3QoF21zhvAh\\/xhb9dMUPCu3kNyJTvAhgPrVOJSI+uaPY8Vak\\/B2AIFQvDnX\\/MjBHTMtWyb2Tki0B8PJ\\/UZ5D\\/CNsxS8l0oa61nGL+KG4hN8nwiTPJ\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1066-john.doe-0' for key 'tp_ident'"]},{"file":"/WEBROOT/NEXTCLOUDPATH/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":1071,"function":"driverExceptionDuringQuery","class":"Doctrine\\DBAL\\DBALException","type":"::","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDOMySql\\Driver"},{"errorInfo":["23000",1062,"Duplicate entry '1066-john.doe-0' for key 'tp_ident'"],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"},"UPDATE `oc_talk_participants` SET `session_id` = ?, `in_call` = ? WHERE (`user_id` = ?) AND (`room_id` = ?) AND (`participant_type` <> ?) AND (`session_id` = ?)",{"1":"0","2":0,"3":"john.doe","4":1066,"5":5,"6":"EOED8Ji5MoxQZ3MtirpKRHYmunk4nBK6VsrQsuMZxQVJpnMSHWqWyZswgw8SDdMcPbs5JONBMM0hoxu2ln8PaLUCAcBUAgWNSr3BbsR68S1kSHr5h6KKGr6ve+Xuzl4CW/y8AMAVIG2Iss3QoF21zhvAh/xhb9dMUPCu3kNyJTvAhgPrVOJSI+uaPY8Vak/B2AIFQvDnX/MjBHTMtWyb2Tki0B8PJ/UZ5D/CNsxS8l0oa61nGL+KG4hN8nwiTPJ"}]},{"file":"/WEBROOT/NEXTCLOUDPATH/lib/private/DB/Connection.php","line":222,"function":"executeUpdate","class":"Doctrine\\DBAL\\Connection","type":"->","args":["UPDATE `oc_talk_participants` SET `session_id` = ?, `in_call` = ? WHERE (`user_id` = ?) AND (`room_id` = ?) AND (`participant_type` <> ?) AND (`session_id` = ?)",["0",0,"john.doe",1066,5,"EOED8Ji5MoxQZ3MtirpKRHYmunk4nBK6VsrQsuMZxQVJpnMSHWqWyZswgw8SDdMcPbs5JONBMM0hoxu2ln8PaLUCAcBUAgWNSr3BbsR68S1kSHr5h6KKGr6ve+Xuzl4CW/y8AMAVIG2Iss3QoF21zhvAh/xhb9dMUPCu3kNyJTvAhgPrVOJSI+uaPY8Vak/B2AIFQvDnX/MjBHTMtWyb2Tki0B8PJ/UZ5D/CNsxS8l0oa61nGL+KG4hN8nwiTPJ"],[2,1,2,1,1,2]]},{"file":"/WEBROOT/NEXTCLOUDPATH/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php","line":209,"function":"executeUpdate","class":"OC\\DB\\Connection","type":"->","args":["UPDATE `oc_talk_participants` SET `session_id` = :dcValue1, `in_call` = :dcValue2 WHERE (`user_id` = :dcValue3) AND (`room_id` = :dcValue4) AND (`participant_type` <> :dcValue5) AND (`session_id` = :dcValue6)",{"dcValue1":"0","dcValue2":0,"dcValue3":"john.doe","dcValue4":1066,"dcValue5":5,"dcValue6":"EOED8Ji5MoxQZ3MtirpKRHYmunk4nBK6VsrQsuMZxQVJpnMSHWqWyZswgw8SDdMcPbs5JONBMM0hoxu2ln8PaLUCAcBUAgWNSr3BbsR68S1kSHr5h6KKGr6ve+Xuzl4CW/y8AMAVIG2Iss3QoF21zhvAh/xhb9dMUPCu3kNyJTvAhgPrVOJSI+uaPY8Vak/B2AIFQvDnX/MjBHTMtWyb2Tki0B8PJ/UZ5D/CNsxS8l0oa61nGL+KG4hN8nwiTPJ"},{"dcValue1":2,"dcValue2":1,"dcValue3":2,"dcValue4":1,"dcValue5":1,"dcValue6":2}]},{"file":"/WEBROOT/NEXTCLOUDPATH/lib/private/DB/QueryBuilder/QueryBuilder.php","line":217,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"/WEBROOT/NEXTCLOUDPATH/apps/spreed/lib/Room.php","line":879,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/WEBROOT/NEXTCLOUDPATH/apps/spreed/lib/Room.php","line":855,"function":"leaveRoomAsParticipant","class":"OCA\\Talk\\Room","type":"->","args":[{"__class__":"OCA\\Talk\\Participant"},null]},{"file":"/WEBROOT/NEXTCLOUDPATH/apps/spreed/lib/Controller/RoomController.php","line":392,"function":"leaveRoom","class":"OCA\\Talk\\Room","type":"->","args":["john.doe"]},{"file":"/WEBROOT/NEXTCLOUDPATH/apps/spreed/lib/Controller/RoomController.php","line":235,"function":"formatRoomV1","class":"OCA\\Talk\\Controller\\RoomController","type":"->","args":[{"__class__":"OCA\\Talk\\Room"},{"__class__":"OCA\\Talk\\Participant"}]},{"file":"/WEBROOT/NEXTCLOUDPATH/apps/spreed/lib/Controller/RoomController.php","line":188,"function":"formatRoom","class":"OCA\\Talk\\Controller\\RoomController","type":"->","args":[{"__class__":"OCA\\Talk\\Room"},{"__class__":"OCA\\Talk\\Participant"}]},{"file":"/WEBROOT/NEXTCLOUDPATH/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"getRooms","class":"OCA\\Talk\\Controller\\RoomController","type":"->","args":[0]},{"file":"/WEBROOT/NEXTCLOUDPATH/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Talk\\Controller\\RoomController"},"getRooms"]},{"file":"/WEBROOT/NEXTCLOUDPATH/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Talk\\Controller\\RoomController"},"getRooms"]},{"file":"/WEBROOT/NEXTCLOUDPATH/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Talk\\Controller\\RoomController","getRooms",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"action":null,"apiVersion":"v1","_route":"ocs.spreed.Room.getRooms"}]},{"file":"/WEBROOT/NEXTCLOUDPATH/ocs/v1.php","line":88,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/apps/spreed/api/v1/room"]},{"file":"/WEBROOT/NEXTCLOUDPATH/ocs/v2.php","line":24,"args":["/WEBROOT/NEXTCLOUDPATH/ocs/v1.php"],"function":"require_once"}],"File":"/WEBROOT/NEXTCLOUDPATH/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php","Line":55,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDOException","Message":"SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1066-john.doe-0' for key 'tp_ident'","Code":"23000","Trace":[{"file":"/WEBROOT/NEXTCLOUDPATH/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":1062,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDOStatement","type":"->","args":[]},{"file":"/WEBROOT/NEXTCLOUDPATH/lib/private/DB/Connection.php","line":222,"function":"executeUpdate","class":"Doctrine\\DBAL\\Connection","type":"->","args":["UPDATE `oc_talk_participants` SET `session_id` = ?, `in_call` = ? WHERE (`user_id` = ?) AND (`room_id` = ?) AND (`participant_type` <> ?) AND (`session_id` = ?)",["0",0,"john.doe",1066,5,"EOED8Ji5MoxQZ3MtirpKRHYmunk4nBK6VsrQsuMZxQVJpnMSHWqWyZswgw8SDdMcPbs5JONBMM0hoxu2ln8PaLUCAcBUAgWNSr3BbsR68S1kSHr5h6KKGr6ve+Xuzl4CW/y8AMAVIG2Iss3QoF21zhvAh/xhb9dMUPCu3kNyJTvAhgPrVOJSI+uaPY8Vak/B2AIFQvDnX/MjBHTMtWyb2Tki0B8PJ/UZ5D/CNsxS8l0oa61nGL+KG4hN8nwiTPJ"],[2,1,2,1,1,2]]},{"file":"/WEBROOT/NEXTCLOUDPATH/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php","line":209,"function":"executeUpdate","class":"OC\\DB\\Connection","type":"->","args":["UPDATE `oc_talk_participants` SET `session_id` = :dcValue1, `in_call` = :dcValue2 WHERE (`user_id` = :dcValue3) AND (`room_id` = :dcValue4) AND (`participant_type` <> :dcValue5) AND (`session_id` = :dcValue6)",{"dcValue1":"0","dcValue2":0,"dcValue3":"john.doe","dcValue4":1066,"dcValue5":5,"dcValue6":"EOED8Ji5MoxQZ3MtirpKRHYmunk4nBK6VsrQsuMZxQVJpnMSHWqWyZswgw8SDdMcPbs5JONBMM0hoxu2ln8PaLUCAcBUAgWNSr3BbsR68S1kSHr5h6KKGr6ve+Xuzl4CW/y8AMAVIG2Iss3QoF21zhvAh/xhb9dMUPCu3kNyJTvAhgPrVOJSI+uaPY8Vak/B2AIFQvDnX/MjBHTMtWyb2Tki0B8PJ/UZ5D/CNsxS8l0oa61nGL+KG4hN8nwiTPJ"},{"dcValue1":2,"dcValue2":1,"dcValue3":2,"dcValue4":1,"dcValue5":1,"dcValue6":2}]},{"file":"/WEBROOT/NEXTCLOUDPATH/lib/private/DB/QueryBuilder/QueryBuilder.php","line":217,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"/WEBROOT/NEXTCLOUDPATH/apps/spreed/lib/Room.php","line":879,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/WEBROOT/NEXTCLOUDPATH/apps/spreed/lib/Room.php","line":855,"function":"leaveRoomAsParticipant","class":"OCA\\Talk\\Room","type":"->","args":[{"__class__":"OCA\\Talk\\Participant"},null]},{"file":"/WEBROOT/NEXTCLOUDPATH/apps/spreed/lib/Controller/RoomController.php","line":392,"function":"leaveRoom","class":"OCA\\Talk\\Room","type":"->","args":["john.doe"]},{"file":"/WEBROOT/NEXTCLOUDPATH/apps/spreed/lib/Controller/RoomController.php","line":235,"function":"formatRoomV1","class":"OCA\\Talk\\Controller\\RoomController","type":"->","args":[{"__class__":"OCA\\Talk\\Room"},{"__class__":"OCA\\Talk\\Participant"}]},{"file":"/WEBROOT/NEXTCLOUDPATH/apps/spreed/lib/Controller/RoomController.php","line":188,"function":"formatRoom","class":"OCA\\Talk\\Controller\\RoomController","type":"->","args":[{"__class__":"OCA\\Talk\\Room"},{"__class__":"OCA\\Talk\\Participant"}]},{"file":"/WEBROOT/NEXTCLOUDPATH/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"getRooms","class":"OCA\\Talk\\Controller\\RoomController","type":"->","args":[0]},{"file":"/WEBROOT/NEXTCLOUDPATH/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Talk\\Controller\\RoomController"},"getRooms"]},{"file":"/WEBROOT/NEXTCLOUDPATH/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Talk\\Controller\\RoomController"},"getRooms"]},{"file":"/WEBROOT/NEXTCLOUDPATH/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Talk\\Controller\\RoomController","getRooms",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"action":null,"apiVersion":"v1","_route":"ocs.spreed.Room.getRooms"}]},{"file":"/WEBROOT/NEXTCLOUDPATH/ocs/v1.php","line":88,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/apps/spreed/api/v1/room"]},{"file":"/WEBROOT/NEXTCLOUDPATH/ocs/v2.php","line":24,"args":["/WEBROOT/NEXTCLOUDPATH/ocs/v1.php"],"function":"require_once"}],"File":"/WEBROOT/NEXTCLOUDPATH/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php","Line":129,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1066-john.doe-0' for key 'tp_ident'","Code":"23000","Trace":[{"file":"/WEBROOT/NEXTCLOUDPATH/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php","line":127,"function":"execute","class":"PDOStatement","type":"->","args":[null]},{"file":"/WEBROOT/NEXTCLOUDPATH/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":1062,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDOStatement","type":"->","args":[]},{"file":"/WEBROOT/NEXTCLOUDPATH/lib/private/DB/Connection.php","line":222,"function":"executeUpdate","class":"Doctrine\\DBAL\\Connection","type":"->","args":["UPDATE `oc_talk_participants` SET `session_id` = ?, `in_call` = ? WHERE (`user_id` = ?) AND (`room_id` = ?) AND (`participant_type` <> ?) AND (`session_id` = ?)",["0",0,"john.doe",1066,5,"EOED8Ji5MoxQZ3MtirpKRHYmunk4nBK6VsrQsuMZxQVJpnMSHWqWyZswgw8SDdMcPbs5JONBMM0hoxu2ln8PaLUCAcBUAgWNSr3BbsR68S1kSHr5h6KKGr6ve+Xuzl4CW/y8AMAVIG2Iss3QoF21zhvAh/xhb9dMUPCu3kNyJTvAhgPrVOJSI+uaPY8Vak/B2AIFQvDnX/MjBHTMtWyb2Tki0B8PJ/UZ5D/CNsxS8l0oa61nGL+KG4hN8nwiTPJ"],[2,1,2,1,1,2]]},{"file":"/WEBROOT/NEXTCLOUDPATH/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php","line":209,"function":"executeUpdate","class":"OC\\DB\\Connection","type":"->","args":["UPDATE `oc_talk_participants` SET `session_id` = :dcValue1, `in_call` = :dcValue2 WHERE (`user_id` = :dcValue3) AND (`room_id` = :dcValue4) AND (`participant_type` <> :dcValue5) AND (`session_id` = :dcValue6)",{"dcValue1":"0","dcValue2":0,"dcValue3":"john.doe","dcValue4":1066,"dcValue5":5,"dcValue6":"EOED8Ji5MoxQZ3MtirpKRHYmunk4nBK6VsrQsuMZxQVJpnMSHWqWyZswgw8SDdMcPbs5JONBMM0hoxu2ln8PaLUCAcBUAgWNSr3BbsR68S1kSHr5h6KKGr6ve+Xuzl4CW/y8AMAVIG2Iss3QoF21zhvAh/xhb9dMUPCu3kNyJTvAhgPrVOJSI+uaPY8Vak/B2AIFQvDnX/MjBHTMtWyb2Tki0B8PJ/UZ5D/CNsxS8l0oa61nGL+KG4hN8nwiTPJ"},{"dcValue1":2,"dcValue2":1,"dcValue3":2,"dcValue4":1,"dcValue5":1,"dcValue6":2}]},{"file":"/WEBROOT/NEXTCLOUDPATH/lib/private/DB/QueryBuilder/QueryBuilder.php","line":217,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"/WEBROOT/NEXTCLOUDPATH/apps/spreed/lib/Room.php","line":879,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/WEBROOT/NEXTCLOUDPATH/apps/spreed/lib/Room.php","line":855,"function":"leaveRoomAsParticipant","class":"OCA\\Talk\\Room","type":"->","args":[{"__class__":"OCA\\Talk\\Participant"},null]},{"file":"/WEBROOT/NEXTCLOUDPATH/apps/spreed/lib/Controller/RoomController.php","line":392,"function":"leaveRoom","class":"OCA\\Talk\\Room","type":"->","args":["john.doe"]},{"file":"/WEBROOT/NEXTCLOUDPATH/apps/spreed/lib/Controller/RoomController.php","line":235,"function":"formatRoomV1","class":"OCA\\Talk\\Controller\\RoomController","type":"->","args":[{"__class__":"OCA\\Talk\\Room"},{"__class__":"OCA\\Talk\\Participant"}]},{"file":"/WEBROOT/NEXTCLOUDPATH/apps/spreed/lib/Controller/RoomController.php","line":188,"function":"formatRoom","class":"OCA\\Talk\\Controller\\RoomController","type":"->","args":[{"__class__":"OCA\\Talk\\Room"},{"__class__":"OCA\\Talk\\Participant"}]},{"file":"/WEBROOT/NEXTCLOUDPATH/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"getRooms","class":"OCA\\Talk\\Controller\\RoomController","type":"->","args":[0]},{"file":"/WEBROOT/NEXTCLOUDPATH/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Talk\\Controller\\RoomController"},"getRooms"]},{"file":"/WEBROOT/NEXTCLOUDPATH/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Talk\\Controller\\RoomController"},"getRooms"]},{"file":"/WEBROOT/NEXTCLOUDPATH/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Talk\\Controller\\RoomController","getRooms",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"action":null,"apiVersion":"v1","_route":"ocs.spreed.Room.getRooms"}]},{"file":"/WEBROOT/NEXTCLOUDPATH/ocs/v1.php","line":88,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/apps/spreed/api/v1/room"]},{"file":"/WEBROOT/NEXTCLOUDPATH/ocs/v2.php","line":24,"args":["/WEBROOT/NEXTCLOUDPATH/ocs/v1.php"],"function":"require_once"}],"File":"/WEBROOT/NEXTCLOUDPATH/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php","Line":127}},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (iOS) Nextcloud-Talk v10.2.1","version":"20.0.4.0"}`

**Comment by nickvergessen** [comment]
@Shen totally unrelated to the iOS app.
But you seem to have duplicate entries in your database. Check the oc_talk_participants for duplicates any manually delete them:
```sql
SELECT `user_id`, `room_id`, COUNT(*) FROM `oc_talk_participants` WHERE `user_id` <> '' GROUP BY `user_id`, `room_id` HAVING COUNT(*) > 1
```

**Comment by Shen** [comment]
> @Shen totally unrelated to the iOS app.
> But you seem to have duplicate entries in your database. Check the oc_talk_participants for duplicates any manually delete them:
> 
> ```sql
> SELECT `user_id`, `room_id`, COUNT(*) FROM `oc_talk_participants` WHERE `user_id` <> '' GROUP BY `user_id`, `room_id` HAVING COUNT(*) > 1
> ```

Thank you! This solved my problem.

**Comment by t-markmann** [comment]
Same here. 16 users with duplicate entries: all were with last_ping 0
Only the iOs app was not able to load correctly - webapp and android had no issues.
