### ISSUE TITLE
Icons for public & groups calls

### ISSUE THREAD

**Issue by mario** [nextcloud/talk-ios#45]
Please use this:

https://material.io/icons/#ic_link
https://material.io/icons/#ic_group

**Comment by Ivansss** [comment]
I think we should keep consistency with the web UI here.
So we should use:
https://github.com/nextcloud/server/blob/master/core/img/actions/public.svg
https://github.com/nextcloud/server/blob/master/core/img/places/contacts-dark.svg
cc @jancborchardt

**Comment by mario** [comment]
Web should use material icons :p

**Comment by mario** [comment]
@jancborchardt poke for opinion.

**Comment by jancborchardt** [comment]
We should use the icons from the server for consistency.

(Sooner or later we should anyway have the group/public call icons change to be a mix of the avatars of the people inside the call + the icon overlaid, rather than _only_ the icon.)

**Comment by mario** [comment]
@jancborchardt I agree with the avatars except it gets messy when you have more than 4 avatars :)
As for the icons, understood - closing this issue then.

**Comment by jancborchardt** [comment]
@mario yeah, for 4+ people we should do a 2*2 grid in the little circle. Above that doesn't really need to be visualized.
