### ISSUE TITLE
Detect when user is talking and send proper data channel messages.

### ISSUE THREAD

**Issue by Ivansss** [nextcloud/talk-ios#46]
- [x] Send speaking/stoppedSpeaking datachannel messages.

**Comment by mario** [comment]
At least on Android, this seems to be done automatically? Look at the logs.

**Comment by mario** [comment]
cc @Ivansss ^_^

**Comment by Ivansss** [comment]
@mario What logs? I pinged you in IRC.

**Comment by mario** [comment]
@Ivansss and answered :P
