### ISSUE TITLE
Update for inputbar design

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/talk-ios#484]
As talk-web is updating the inputbar in talk 11, I was thinking about adpating some design changes to talk-ios.

**Current**

Light | Dark
------------ | -------------
![IMG_1382](https://user-images.githubusercontent.com/1580193/106390318-1ae96d00-63e8-11eb-9b73-c28e4f179afe.PNG)|![IMG_1381](https://user-images.githubusercontent.com/1580193/106390327-2046b780-63e8-11eb-9abe-9fc8e712a5aa.PNG)

**1. Rounded corners and adjusted top border**

Light | Dark
------------ | -------------
![IMG_1383](https://user-images.githubusercontent.com/1580193/106390377-79165000-63e8-11eb-9c42-27e0ba1d86a7.PNG)|![IMG_1384](https://user-images.githubusercontent.com/1580193/106390382-7e739a80-63e8-11eb-831e-2d3dbef99484.PNG)

**2. + no secondary background**

Light | Dark
------------ | -------------
![IMG_1371](https://user-images.githubusercontent.com/1580193/106390447-d5796f80-63e8-11eb-9306-20bcfbda3624.PNG)|![IMG_1372](https://user-images.githubusercontent.com/1580193/106390453-d9a58d00-63e8-11eb-858b-8daff8cc13a7.PNG)

**3. + top border only when scrolled**

Light | Dark
------------ | -------------
![IMG_1377](https://user-images.githubusercontent.com/1580193/106390482-fb067900-63e8-11eb-90d7-b2221863bbb2.PNG)|![IMG_1376](https://user-images.githubusercontent.com/1580193/106390486-fe016980-63e8-11eb-959d-a07886f43cd5.PNG)
![IMG_1378](https://user-images.githubusercontent.com/1580193/106390517-16718400-63e9-11eb-84b1-94c373a480b0.PNG)|![IMG_1380](https://user-images.githubusercontent.com/1580193/106390526-183b4780-63e9-11eb-8327-27d44de129a6.PNG)

**4. when first responder**

Light | Dark
------------ | -------------
![IMG_1373](https://user-images.githubusercontent.com/1580193/106390587-59cbf280-63e9-11eb-831f-7d80a0643085.PNG)|![IMG_1375](https://user-images.githubusercontent.com/1580193/106390592-5d5f7980-63e9-11eb-9e3d-acbc73478d10.PNG)

4. Is only there for reference and could be used with any of the other 3. Although I can't think of any other app that highlights the border of a textinput on iOS, so not sure if we should do this.

Note that those screenshots were done on an iPhone with a bezel. We might need to check if this works on bezel-free devices as well.

**Comment by SystemKeeper** [comment]
@nextcloud/designers-talk

**Comment by marcoambrosini** [comment]
Good work @SystemKeeper!
I would say let's keep it consistent with what we have in the web version, so option 3. The only thing that doesn't feel right is the space on top and bottom of the input field. It seems a bit small to me. We could check out the sizing of the elements in iMessage.
As per the highlighted (border) input, I don't think it's necessary

**Comment by SystemKeeper** [comment]
Thx @ma12-co !

The space in iMessage is nearly identical to what it's now in talk-ios, only the inputbar itself is a bit higher (and the font size looks a bit larger too): 
![image](https://user-images.githubusercontent.com/1580193/107985646-c25ec600-6fca-11eb-936f-ee42a6e5839a.png)
![image](https://user-images.githubusercontent.com/1580193/107985737-f0dca100-6fca-11eb-84bc-9bb918abc8e0.png)

**Comment by marcoambrosini** [comment]
Ok. Then let's keep the margins as they are. Though now that you mention it, it seems reasonable to increase the height of the input field as well for easier tapping, don't you think?

**Comment by SystemKeeper** [comment]
Okay! I already increased the size of the inputbar a bit in the PR. The difference to iMessage is now around 3px. We can go a bit larger, but this needs some additional adjustments to the button height, as those wouldn't be centered anymore. @Ivansss had some adjustments planned to the button height, so I guess we should visit this again in another PR.
