### ISSUE TITLE
Last message ellipse

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-ios#489]
Last message in conversation list is cut off instead of ellipsed to indicate it continues

![image](https://user-images.githubusercontent.com/213943/107115019-07b42280-686a-11eb-91ab-b011f1a5cc22.jpeg)

![image](https://user-images.githubusercontent.com/213943/107115022-0c78d680-686a-11eb-8edf-f42f7224512c.jpeg)

**Comment by Ivansss** [comment]
Fixed in f5dbbc6cc8a993d145c2fc654789c1480eee2dd0
