### ISSUE TITLE
traditional Chinese version

### ISSUE THREAD

**Issue by wenpinglee** [nextcloud/talk-ios#494]
Is there some chance to get multi language support in this talk app?

I look forward to the traditional Chinese version of this app.

Thanks

**Comment by Ivansss** [comment]
Hi @wenpinglee :)
We introduced multi language support in [version 10.1.0](https://github.com/nextcloud/talk-ios/releases/tag/v10.1.0).
We are planning to add more languages in version 11 (it will be released next week) and Chinese will be one of those languages that we will add for this version ;)

**Comment by wenpinglee** [comment]
Awesome!  Thanks for your reply😄

**Comment by Ivansss** [comment]
Added Chinese (Simplified) in 8224988c51561ed04e0622d2268e2781564cdc51
