### ISSUE TITLE
Problem with installing from Xcode

### ISSUE THREAD

**Issue by framarini02** [nextcloud/talk-ios#496]
how can I install the app from Xcode?  because when i try to do it i have to put my developer account and this leads to errors

**Comment by framarini02** [comment]
otherwise is it possible to test the app using TestFlight?

**Comment by SystemKeeper** [comment]
Currently you can't test this app using TestFlight, of course the latest release is available on the app store. Is there something in particular you wanna test?

When you want to do some coding on XCode you can either run it in simulator (this shouldn't need many changes to the master branch), but when you want to run it on device, you need to put in your dev account, change the group identifier and adjust the settings in NCAppBranding.m accordingly. Note that then of course push notifications won't work for you.

**Comment by framarini02** [comment]
I wanted to try out the latest graphical changes and the ability to move our camera frame

**Comment by Ivansss** [comment]
Hi @framarini02,

As @SystemKeeper said, you should be able to run the app using XCode. You just need to change the bundle id (in "General" section) and set your Apple developer account (in "Signing & Capabilities" section).

There will be a release Talk 11 this week. And I will put a public link for Testflight in the README of this repository.
