### ISSUE TITLE
Cannot get account info, conversations, list of contacts

### ISSUE THREAD

**Issue by mr-eshua** [nextcloud/talk-ios#497]
Hi,

I'm trying to connect to next cloud instance with iOS Talk app. Authorization goes smoothly, but after that there are no conversations, contacts or even account info is not shown. No errors appear or anything that may tell what is the problem. Web instance and official nextcloud iOS app work fine in the same time.

Appreciate any help. Let me know if I can provide some more info to investigate.
![image](https://user-images.githubusercontent.com/22781783/108601107-f01d8380-73ab-11eb-912e-cb61e9e0a200.jpeg)
![image](https://user-images.githubusercontent.com/22781783/108601110-f6abfb00-73ab-11eb-8386-fd9d0dbae0b7.jpeg)
![image](https://user-images.githubusercontent.com/22781783/108601113-fa3f8200-73ab-11eb-8a70-7eb7fffafc79.jpeg)

**Comment by SystemKeeper** [comment]
Which NC server version and talk version are you currently running?
It's interesting that you no username is visible in your screenshots. Are there any special characters in your username?

**Comment by mr-eshua** [comment]
Talk iOS app: 10.3.1
Talk server: 10.0.5
NC server: 20.0.7

Yeah, app is completely unusable. Username is of just ascii chars, should be: Roma.

**Comment by Ivansss** [comment]
Hi @mr-eshua,

Do you see any errors in the nextcloud log?
Your issue sounds similiar to https://github.com/nextcloud/talk-ios/issues/448

**Comment by SystemKeeper** [comment]
Any news here @mr-eshua ?

**Comment by mr-eshua** [comment]
Hey @SystemKeeper, sorry. Currently, I've no access to NC server to check out the logs, but I'll try to contact server admin and will see if it's something similar. Let you know ASAP.

Thanks @Ivansss for pointing that out for me.

**Comment by mr-eshua** [comment]
I figured that out. It seems that #448 is not related to this. I used full URL to the server with "https://..." and it worked. Might be related to the server domain configuration somehow.

Anyway, problem solved. Thanks for the assistance! Can be closed, I guess.

**Comment by SystemKeeper** [comment]
Interesting, this should happen automatically 
https://github.com/nextcloud/talk-ios/blob/f7cd09ea85fcda1f61cea3d758a441e366492baf/NextcloudTalk/LoginViewController.m#L109-L111

Just to make sure, before you had „cloud.domain.tld“ which did not work, but setting „https://cloud.domain.tld“ did work for you?

**Comment by mr-eshua** [comment]
> Just to make sure, before you had „cloud.domain.tld“ which did not work, but setting „[https://cloud.domain.tld“](https://cloud.domain.tld%E2%80%9C) did work for you?

Well not exactly, instead of "cloud.domain.tld" I used "https://www.cloud.domain.tld". And since the code you showed covers the "https://" part automatically, I assume the reason is that "www." part. I haven't checked yet exactly, but seems like it is unrealated to Talk app at all.

**Comment by Ivansss** [comment]
Thanks for the info @mr-eshua ;)
And happy to hear that it's working as expected for your now :)
I will close this issue then.

**Comment by mr-eshua** [comment]
Thanks a lot for being here to help @Ivansss and @SystemKeeper 😃
