### ISSUE TITLE
Remarks for call view enhancements

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/talk-ios#498]
Ref #495 

Some remarks, some might be intended.

* Local video frame is "visible" (you see the switch camera icon and can move it around) although there's no local camera (simulator and I guess would be the case for a mac without a cam)
* Audio button won't stay visible when muted, so now push-to-talk needs an additional tap to show the buttons first and then activate push-to-talk. The change at https://github.com/nextcloud/talk-ios/pull/495/commits/40b5910e3e59dba0a22be0837198c43913b8fc58#diff-fc49062740b3d2bdc2d6751f66aa1b4b67d303423578c961b1f251d16d0eefcbL559-R577 is responsible for this, that's the reason the individual icons were hidden instead of the container.
* Local video is between back-to-call-button and its halo: 
![image](https://user-images.githubusercontent.com/1580193/108630491-59150200-7465-11eb-849d-f9da59c18665.png)
* Chat icon is not updated to material design  (https://material.io/resources/icons/?search=chat&style=baseline)
* Button container does not respect safe-area, was better before: 
![image](https://user-images.githubusercontent.com/1580193/108630657-291a2e80-7466-11eb-879f-b6b68b82e257.png)
![image](https://user-images.githubusercontent.com/1580193/108630665-30d9d300-7466-11eb-9900-71cfc4172392.png)
* When having a call and you go to chat -> open the conversation info -> you're unable to tap on anything (intended?). Long pressing on the other hand works... ?!

**Comment by Ivansss** [comment]
> When having a call and you go to chat -> open the conversation info -> you're unable to tap on anything (intended?). Long pressing on the other hand works... ?!

Not intended and can't reproduce this one :S

**Comment by SystemKeeper** [comment]
It works when I'm the only one in the call. When there's another participant in the call it doesn't work :S

**Comment by Ivansss** [comment]
You are right! It only happens in videocalls.
It's because of the TapGestureRecognizer we use for the detailedView.
Fix incoming ;)
