### ISSUE TITLE
Push-to-talk stays active when screen gets disabled through proximity

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/talk-ios#499]
Steps to reproduce

* Mute yourself
* Tap and hold on the mute icon to activate push-to-talk (green halo appears)
* Trigger the proximity sensor to turn-off the camera and the screen
* Notice that push-to-talk now stays active even after stop releasing the button

**Comment by Ivansss** [comment]
Nice catch 😅 Fixed in 191c9fdb67a9ab8c5bdcbd4950a187b0ebee030d

**Comment by SystemKeeper** [comment]
Although this fixes the problem, wouldn't it make more sense to do it the other way round? Don't disable the screen while push-to-talk is active?
