### ISSUE TITLE
Active Directory Users Talk app crashing

### ISSUE THREAD

**Issue by PiotrIr** [nextcloud/talk-ios#50]
I’m testing Nextcloud 13 RC4 and having some problem with Talk application on my IPhone. When I login using local credentials (created in Nextcloud directly), everything is working perfectly fine. I can make video call without any problems. However when I login using Active directory user and try to establish call, application closes directly after another person joins.

**Comment by mario** [comment]
@PiotrIr first of all, thank you for the bug report. Could you please create two test accounts and send them to me? mario AT nextcloud.com

**Comment by PiotrIr** [comment]
Hi Mario,

Could you advise how I will send them please?

**Comment by mario** [comment]
@PiotrIr to my mail :) mario AT nextcloud.com :)

**Comment by mario** [comment]
@PiotrIr found the issue, we're working on the fix :)

**Comment by PiotrIr** [comment]
Hi Mario,

That is great! Can I disable testing account or do you still need them?

Kind Regards
Piotr

**Comment by mario** [comment]
Not yet please, we need them :)

**Comment by Ivansss** [comment]
Hi @PiotrIr 
Thanks for reporting the bug and creating test accounts for us. 😊 
The issue has been fixed and will be included in the next app release 1.2.0.
Version 1.2.0 will be released soon (this week).
You can now disable test accounts if you don't need them.

**Comment by PiotrIr** [comment]
Thank you Ivan, really impressed how you resolved issues 😊
