### ISSUE TITLE
Talk app direct link

### ISSUE THREAD

**Issue by wenpinglee** [nextcloud/talk-ios#500]
I used this code "Nextcloud://directlink/" can open Nextcloud APP,but can't open "Nextcloud Talk APP".
 Is there any other code to open "Nextcloud Talk APP"?

Thanks you.

**Comment by Ivansss** [comment]
There is no scheme that opens the Nextcloud Talk app at the moment.
What are you trying to implement? :)

**Comment by wenpinglee** [comment]
I want to set a web button what can directly connect to Nextcloud Talk APP dialog box.

Thanks ^_^

**Comment by SystemKeeper** [comment]
Something like https://github.com/nextcloud/talk-ios/issues/234 ?

**Comment by wenpinglee** [comment]
Yes.
Will this update in future version?

**Comment by Ivansss** [comment]
> Will this update in future version?

It might be implemented in a future version yes.
Let's close this issue and continue in favor of #234
