### ISSUE TITLE
On sharing of Nextcloud folders / files cannot be selected below certain subfolder level

### ISSUE THREAD

**Issue by freundhein** [nextcloud/talk-ios#503]
### Test Setup:
- iOS 14.4 / iPhone 11 / Talk App 11.0.0 (but also seen on 10.3.1)
- NC Server 20.0.7 / Talk Server App 10.0.6 (but also seen on 10.0.5)

### Expected Behavior 
In a specific chat when starting file sharing by pressing the paper clip symbol and selecting "Nextcloud" the folder/file selector opens on top level of folder structure. From there any subfolders can be selected/opened recursively to any subfolder level.

###  Actual Behavior
Folder/files selector opens on top level
When selecting any folder there it opens and content (subfolders and files) is shown on 1st sublevel
But when again selecting any folder then the spinning wheel pops up and rotates forever, and subfolder's content on 2nd sublevel will not be shown.

### x-checks done
1. on Android phones sharing works to the 4th level at least
2. on Webbrowser sharing works down to the same level, too

**Comment by SystemKeeper** [comment]
When there's a folder structure like "Test -> Test2" Test can be accessed fine, but when selecting Test2 we actually try to get TestTest2

```
        <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
          <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
          <s:message>File with name TestTest2 could not be located</s:message>
        </d:error>
```

**Comment by freundhein** [comment]
yes, now as you mention it: that's even listed that way in the app's headline

**Comment by SystemKeeper** [comment]
Yes, thanks for the report! Looks like there‘s something wrong with combining the paths.

**Comment by Ivansss** [comment]
Thanks for reporting the issue @freundhein :)
There will be a release (v11.0.1) this week and the bugfix will be included.

**Comment by freundhein** [comment]
welcome! thanks for fixing it so quickly

> Thanks for reporting the issue @freundhein :)
> There will be a release (v11.0.1) this week and the bugfix will be included.

welcome! thanks for fixing it so quickly
