### ISSUE TITLE
No notifications about messages  from iOS app. ver 11.0.0

### ISSUE THREAD

**Issue by chosebine501** [nextcloud/talk-ios#508]
No notifications about messages  from iOS app. since ver 11.0.0
it's the same issues that in june 1918!!!!
this problem is the return...
https://help.nextcloud.com/t/no-notifications-nextcloud-talk-ios-chat/32642

**Comment by SystemKeeper** [comment]
So notifications worked fine for you in v10.3.1 then? Because I don't see notification related changes between 10.3.1 and 11.0.0: https://github.com/nextcloud/talk-ios/compare/v10.3.1...v11.0.0 

Just to make sure:
* Are just chat-notifications missing or call-notifications as well?
* Do you have any active talk session in a browser?
* Did you try to logout of talk-ios and login again? (Although this shouldn't be neccessary if it worked before...)
* Anything in the server logs?

**Comment by chosebine501** [comment]
Hi,
Thanks for the replay
I understand, but yes with 10.3.1 it's works.
we use this, for my family and friends.
(ok, my English is not very good, but I try to explain)
First, I update my ipad from 10.3.1 to 11 in the morning, and I didn't receive any more notifications.
In the evening it was my children that they updated and then they were the ones who did not receive any more notifications.
the next day it was my wife who updated to 11.0 and no one received any more notifications.
to give you more details, we receive the first notification and when we open the app to read the message and close the app there is nothing working anymore, if we wait more than 5min, at that moment the IOS receives a new notification.

For you questions:

> - Are just chat-notifications missing or call-notifications as well?  just chat-notifications issues the calls it's work perfectly
>
> - Do you have any active talk session in a browser? no, just on ipad iphone
>
> - Did you try to logout of talk-ios and login again? (Although this shouldn't be neccessary if it worked before...) yes, I did all of that I even uninstall and reinstall
> - Anything in the server logs? Noting

I revoke all Devices & sessions. in my account
I try to update my server from V20 at V21.0.0 and same issues.

Regards

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by SystemKeeper** [comment]
Thanks for the details!
If I understand correctly, sending another message within the 5 minutes won't trigger a notification. What happens if you send to a different chat? (eg. not the same person/group) is then a notification triggered?
Are you using internal or external signaling (aka HPB) ?

**Comment by chosebine501** [comment]
Hi,
Good news for me!
Seeing that seems to be the only one to have this problem, and after trying everything, I decided to a rollback my database to one week from backups. And now the notifications are working again.
It's really quite a coincidence with the updates of the app to v11 (it's really weird)
Unfortunately that doesn't tell me what the problem was. But it works now.
Sorry for blaming the app. ;)

The next step it's try to update my Nextcloud server from 20.8 to 21, I trying this in the next week.

regards

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
