### ISSUE TITLE
enable media playback within a conversation

### ISSUE THREAD

**Issue by sudwhiwdh** [nextcloud/talk-ios#510]
Use case for me would be to be able to play an audio or video file or embedded platform video in Nextcloud Talk in a conversation so that all participants can listen/view it in parallel.
This will be a welcome function, especially in the now mostly digital education work in schools and universities.

Related Issues for Android & the Web Interface
https://github.com/nextcloud/talk-android/issues/1043
https://github.com/nextcloud/spreed/issues/5280

**Comment by nickvergessen** [comment]
Closing until nextcloud/spreed#5280 is solved
