### ISSUE TITLE
Link colour

### ISSUE THREAD

**Issue by PA3LIT0** [nextcloud/talk-ios#539]
Can the colour for links and "add attachment" option be the instance theme colour?

![image](https://user-images.githubusercontent.com/71569166/113947274-957ca180-980a-11eb-9f12-75ef715b048f.jpeg)

![image](https://user-images.githubusercontent.com/71569166/113947359-c8bf3080-980a-11eb-931a-70f00313966c.jpeg)

**Comment by Ivansss** [comment]
Hi @PA3LIT0 :)

We decided to use default action colors here:
System blue for normal actions
System red for destructive actions

This gives the app a more native feeling.
