### ISSUE TITLE
Nextcloud Talk cannot cope with strange ports

### ISSUE THREAD

**Issue by Maulwurf16** [nextcloud/talk-ios#54]
Short story.
I use my Nextcloud behind a DS-Lite (Unitymedia) internet access, and therefore have no public IPv4 address. Thus, I use a Portmapper, which maps my IPv6 Address to something like:

http://some.verystrangeaddress.de:123456/nextcloud

which is public available.

The Nextcloud App (iOS as well as Android) and the desktop sync Clients can cope with this, the chat app however cannot. I assumed, that it was the lack of ssl, but read that you support "normal" http in other issues.

**Comment by Ivansss** [comment]
Hi @Maulwurf16 ,
What do you mean by "the chat app"?
I followed your conversation in https://github.com/nextcloud/talk-android/issues/93 and seems like you can't connect to your server with the iOS app?

**Comment by Maulwurf16** [comment]
I'm sorry @Ivansss . By my sloppy mention of "chat app" I mean the (iOS) nextcloud talk app :).
Your assumption is correct. I try to connect to the server. While the main ios Nextcloud App can connect without any errors, Nextcloud Talk throws an error on connection:
"Nextcloud Talk app not found - Please, check that you enter te correct Nextcloud server url and the Nextcloud Talk app is enabled in that intance"

**Comment by Ivansss** [comment]
Ok 😊 The problem might be related with IPv6.
Thanks for reporting it!

**Comment by mario** [comment]
Either that, or the fact the server would not report port in a base url.

**Comment by mario** [comment]
(Ah, actually, it's probably too early in the workflow so that would be a problem - but it might in the future)

**Comment by Ivansss** [comment]
@Maulwurf16 Could you send me an email with the address of your server?

**Comment by Maulwurf16** [comment]
@Ivansss just did. Let the homepage load for a while, as its just a raspberry running a fully grown Cloud... (awesome :) )

**Comment by Ivansss** [comment]
I see the problem now, I didn't notice before 🙈 
You will need to connect to your server via HTTPS in order to conform Apple's ATS (App Transport Security) policy.

**Comment by Maulwurf16** [comment]
Ah well, another reason to finally embed ssl.
However, thank you so much

**Comment by Maulwurf16** [comment]
Just a convenience update (maybe its useful to others)

With an https proxy (with a signed cert, just as „feste-ip.net“ offers) everything works like a charm - even without a TURN server.
That proxy again maps the portmapper to a https address :D, but it works

**Comment by bcutter** [comment]
It´s quite hard to figure out what is actually needed to get this to work. Nextcloud Talk app on iOS says "Nextcloud Talk app not found". First issue: App on NC server is called "Video calls". Configurations in NC server settings don´t provide any information on where to start. Probably not an "install an app on the NC server, one on a client like iPhone, and things will work PnP out of the box" situation :-) :-(

**Comment by mario** [comment]
Did you configure Turn? :P

**Comment by Ivansss** [comment]
Hi @bcutter 
What Nextcloud version do you use?
The Nextcloud Talk iOS app requires Nextcloud 13 and Nextcloud Talk 3.0.
If the app is called "Video calls" on your server, you are probably running and older NC server version.

**Comment by bcutter** [comment]
As I´m on NC v13(.0.1.1) now the app is working. Had no chance to actually run a session, but everything looks fine so far - without any further configuration regarding Turn etc.

Sorry for abusing this issue.

**Comment by Ivansss** [comment]
No problem at all @bcutter 
Happy to hear that is working now 😊
