### ISSUE TITLE
Every call starts with muted microphone

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-ios#542]
Is this always helpful?
Maybe not if I started the call and if it's a 1:1 call it maybe not helpful, too.

**Comment by Ivansss** [comment]
Hi @jacboy 
Do you mean in the web app or in the iOS app?
Because in the Talk iOS app that shouldn't be the case :S

**Comment by jakobroehrl** [comment]
It's the iOS App. 
Installed the latest version. 
If I start a call the mic is muted, same when I pick up a call.

**Comment by Ivansss** [comment]
I can't reproduce that behaviour and there is no code for making calls start with muted microphone.

**Comment by jakobroehrl** [comment]
Hmm, what can I do?
Had this with 2 different phones.

**Comment by Ivansss** [comment]
What version of Talk iOS are you using?
Does only happen in those 2 phones?
Could you share some steps to reproduce this issue?
Could you maybe share some screen recording showing this issue? :)
