### ISSUE TITLE
Date buttons could become clickable 

### ISSUE THREAD

**Issue by Maria-kamenskaya** [nextcloud/talk-ios#552]
**Is your feature request related to a problem? Please describe.**
If there are a lot of messages it gets hard to find the first one of the specific day. For example, there are already date buttons on the top if you scroll in the chat, like “yesterday”, “21.april”, “19.march” but if you click on it nothing happpens and you have to scroll to find the first message of that day.

**Describe the solution you'd like**
If you click on the date button you will be brought to the first message of that day.

**Describe alternatives you've considered**

**Additional context**

**Comment by Ivansss** [comment]
That will be a really nice enhancement! Thanks for the feedback @Maria-kamenskaya :)

**Comment by Ivansss** [comment]
Implemented in #639
