### ISSUE TITLE
In the chat files unable to come to the first file automatically

### ISSUE THREAD

**Issue by Maria-kamenskaya** [nextcloud/talk-ios#553]
**Is your feature request related to a problem? Please describe.**
If I enter a chat and then tap on the clip icon and then on Nextcloud, I can see all the files. But then I scroll down and if there are too many files, to go back to the top I need to scroll again manually. 

**Describe the solution you'd like**
If you already scrolled to the last file at the bottom, you can click on Home icon to be navigated to the first file on the top. I visualised my solution in figma: https://www.figma.com/file/2X5NVbtdgQS2QyUyDQG1e4/Talk-App-iOS?node-id=0%3A1

**Comment by Ivansss** [comment]
As discussed, this feature is implemented already natively by clicking the status bar.
