### ISSUE TITLE
Previews in original aspect ratio

### ISSUE THREAD

**Issue by lotofbits** [nextcloud/talk-ios#554]
It would be great if photo/video previews were also displayed in the original aspect ratio and slightly larger, as was also recently introduced in the browser version [Chat previews now expanded with aspect ratio #4469](https://github.com/nextcloud/spreed/pull/4469).

**Comment by Ivansss** [comment]
That will be indeed a nice improvement. Thanks for opening this issue @lotofbits :)
Are you a developer? This could be a good first issue for contributors :D

**Comment by lotofbits** [comment]
Good to hear :). Unfortunately, I'm not a developer, just an avid user. @Ivansss

**Comment by SystemKeeper** [comment]
Done in #648
