### ISSUE TITLE
Nextcloud server not found

### ISSUE THREAD

**Issue by elhananjair** [nextcloud/talk-ios#559]
## Steps to reproduce
1. Tap on Nextcloud Talk app
2. Enter URL of Nextcloud Server
3. Tap Log in button

### Expected behaviour
Open browser for grant access to an account 

### Actual behaviour
Showing Error:
Nextcloud server not found, please check that you entered the correct Nextcloud server address

I am using Self Signed Certificate and imported to my iPhone as trusted profile yet its not working. The thing is, it has been working fine with the old talk versions(like I tried 8 month or a year ago. I don't know if updating my iPhone change things. 

## Device information

**Device:** iPhone X/iPad Y/…
iPhone 5S
**iOS version:** 10/…
12.5.1
**Talk version:** 11.1.1
11.1.3
## Server information

**Nextcloud version:** (see admin overview page: `/index.php/settings/admin/overview`)
21.0.1
**Talk version:** (see apps admin page: `/index.php/settings/apps`)
11.2.1
**Custom Signaling server configured:** yes/no and version (see talk admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#turn_server`)
no
**Custom STUN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#stun_server`)
no
### Server log (data/nextcloud.log)
<details>

```
There is no log regarding this issue. 
```
</details>

**Comment by elhananjair** [comment]
I have fixed by enabling the certificate from settings, I enabled the issuer of the certificate in a profile setting but now I enabled the certificate in Trust Certificate setting and it worked.

**Comment by transcendence-x** [comment]
How did you solve it，help!

**Comment by SystemKeeper** [comment]
Hey @chaoqunxie 
If there’s a problem connecting to the server, you might want to check https://help.nextcloud.com/ judging from this ticket it seems there was a problem with trusting the certificate.
If you think there’s a bug, feel free to open a new ticket and fill in as much details as you can provide. Note that there’s currently no known issue with connecting to the server.
