### ISSUE TITLE
Unable to get notification using own bundle identifiers.

### ISSUE THREAD

**Issue by imrun** [nextcloud/talk-ios#560]
I did create certs but where should i put them as i dont see any documentation.

**Comment by Ivansss** [comment]
Hi @imrun 
Unfortunately this is not possible at this moment. 
You will need to deploy your own push proxy server for that and the code of the push proxy is not publicly available at the moment. See https://github.com/nextcloud/notifications/issues/82

**Comment by ElectrifyPowr** [comment]
It is understandable that the full push proxy code is not publicly available.

However, this does not mean that there should be no documentation on this or code snippets on how to achieve this.

I'm sure a lot of people are struggling with this issue @Ivansss 

I imagine anybody will be thankful for some more detailed guidance on how to achieve it.
