### ISSUE TITLE
Sound iPad-->HDMI

### ISSUE THREAD

**Issue by dmod83** [nextcloud/talk-ios#562]
We use an local installation (via snap) for conferences. We share the iPad-Screen via Apple-HDMI-Adapter to beamer (with speakers). The sound of nextcloud talk videocalls is not available on beamer. 

Other apps (like Youtube) are sending sound through HDMI-adapter to beamer. 

**Device:** iPad
**iPadOS version:** 14.6
**Talk version:** latest

## Server information
**Nextcloud version:** latest
**Talk version:**  latest

**Comment by SystemKeeper** [comment]
Selection of audio route was implemented in #735
