### ISSUE TITLE
'NCCommunication/NCCommunication.h' file not found

### ISSUE THREAD

**Issue by asefainno** [nextcloud/talk-ios#564]
1. `git clone https://github.com/nextcloud/talk-ios.git `
2. $ `pod install`
3. $ `git submodule update --init`
4. $ `carthage update --use-xcframeworks --platform ios`
5. $ open NextcloudTalk.xcworkspace

Error 
Path : Project > ShareExtension > ShareConfirmationController.m 

#import <NCCommunication/NCCommunication.h> 

Error on this line -> 'NCCommunication/NCCommunication.h' file not found

Deteil 
Xcode Version 12.5 (12E262)
carthage version 0.38.0
pod version 1.10.1

**Comment by Ivansss** [comment]
Hello @asefainno 

Thanks for opening this issue! I have just updated the build information in the README.

You can now pull latest master and build the project with the following steps:

```
$ pod install

$ git submodule update --init

$ ./carthage.sh update --platform ios (XCode 12+)
  OR
$ carthage update --platform ios (XCode < 12)

$ open NextcloudTalk.xcworkspace
```
