### ISSUE TITLE
new conversation problem

### ISSUE THREAD

**Issue by Smileknight-wang** [nextcloud/talk-ios#567]
There are 80 members in the oc_user datatable,then I open nextcloud talk app,I want to creat a new conversation,it displays only 50 members.

How can I solve this problem?Can I display all of members? 

Thank you very much.

**Comment by Ivansss** [comment]
Hello @Smileknight-wang :)
The app by default fetches a list of 50 users.
You can use the search bar to search for users that are not in that list.
