### ISSUE TITLE
Chat feature

### ISSUE THREAD

**Issue by Maulwurf16** [nextcloud/talk-ios#57]
Hello everybody.

The app works great and I can see it replacing WhatsApp Audio/Video with my Friends. However chat would be even more needed, than Video.

Is it planned to integrate the chat feature from the server talk app? (Or is there a public Roadmap on what's to come).

Best Regards,
Maulwurf

**Comment by emresaracoglu** [comment]
Hi, 

https://twitter.com/nextclouders/status/962297104583528448
