### ISSUE TITLE
logon with email address as username not working

### ISSUE THREAD

**Issue by dtbu** [nextcloud/talk-ios#58]
All users in my nextcloud have email address as username. Logon with talk-ios app failed with the following entries in nextcloud.log:

:“core”,“method”:“GET”,“url”:"/ocs/v2.php/apps/spreed/api/v1/room",“message”:“Login failed: ‘user%40email.de’ (Remote IP: ‘2003:aaaa:13e7:6800:f857:54f0:b764:aaaa’)”,“userAgent”:“Mozilla/5.0 (iOS) Nextcloud-Talk v1.1.0”,“version”:“13.0.0.14”}

I think the problem is that “@” in username is sendings as “%40”, i see the ‘user%40email.de’ also as auth-user in apache access.log instead of ‘user@email.de’.
Logon with the same user and use of talk-app with browser works without any problems.

**Comment by mario** [comment]
The following is Android code:

            if (value.startsWith("user" + LOGIN_URL_DATA_KEY_VALUE_SEPARATOR)) {
                loginData.setUsername(URLDecoder.decode(
                        value.substring(("user" + LOGIN_URL_DATA_KEY_VALUE_SEPARATOR).length())));
            } else if (value.startsWith("password" + LOGIN_URL_DATA_KEY_VALUE_SEPARATOR)) {
                loginData.setToken(URLDecoder.decode(
                        value.substring(("password" + LOGIN_URL_DATA_KEY_VALUE_SEPARATOR).length())));
            } else if (value.startsWith("server" + LOGIN_URL_DATA_KEY_VALUE_SEPARATOR)) {
                loginData.setServerUrl(URLDecoder.decode(
                        value.substring(("server" + LOGIN_URL_DATA_KEY_VALUE_SEPARATOR).length())));

This basically means that you should do URL decoding on received username, password and server url, and then store that.

cc @Ivansss 

This will fix all your issues :P

**Comment by mario** [comment]
Thanks for reporting the bug btw @dtbu

**Comment by mario** [comment]
As for how to fix existing stored users: show "upgrade" screen with progress bar, iterate over all users, and upgrade username, password and server url.

**Comment by Ivansss** [comment]
Thanks for your detailed report @dtbu 
This bugfix will be included in the next (coming soon) release 1.2.0.

**Comment by dtbu** [comment]
Thanks for fixing it 👍
