### ISSUE TITLE
Push notification delay

### ISSUE THREAD

**Issue by charleypeng** [nextcloud/talk-ios#580]
I have a self hosted server, with ntp enabled and time zone set to utc, but the push notification seems to be delayed like about 30seconds, any reason for this.   Thanks

**Comment by charleypeng** [comment]
However, when I make a Video call the notification is just in time

**Comment by chosebine501** [comment]
same problem

**Comment by frieck** [comment]
Same problem here, NC running on a Raspberry Pi 4 8Gb with DietPi.
Is there any special configuration that need to be done?
Thanks

**Comment by Ivansss** [comment]
We are investigating the reason for these delays and how to fix them.

**Comment by Ivansss** [comment]
This issues has been fixed and the bugfix will be included in version 12.1.0 (which will be released today)

**Comment by charleypeng** [comment]
great, thanks
