### ISSUE TITLE
notification on icon ios app

### ISSUE THREAD

**Issue by chosebine501** [nextcloud/talk-ios#581]
## Steps to reproduce
1.all people
2.
3.

### Expected behaviour
Tell us what should happen

we receive all text message with banner preview
but no red point notification on ios app talk.
this issue it's only present with ios talk app 12

### Actual behaviour
Tell us what happens instead

## Device information
all ios
**Device:** iPhone X/iPad Y/…
all iphone and ipad
**iOS version:** 10/…
14,6
**Talk version:** 11.1.1
12
## Server information
talk server 11.2.2
**Nextcloud version:** (see admin overview page: `/index.php/settings/admin/overview`)
nextclous server 21,0,2
**Talk version:** (see apps admin page: `/index.php/settings/apps`)
11.2.2
**Custom Signaling server configured:** yes/no and version (see talk admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#stun_server`)

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by Bryantdl7** [comment]
I am having this problem also. iPhone XR.

**Comment by Ivansss** [comment]
Thanks @chosebine501 for reporting the issue :)
This issue has been fixed and the bugfix will be included in version 12.0.1.

**Comment by chosebine501** [comment]
hi,
How soon do you plan to release version 12.0.1?
thank you

**Comment by kruthoff** [comment]
Yes I'm waiting for this, too. The app usage is limited without badge.

**Comment by Ivansss** [comment]
Version 12.1.0 has been just released. It includes the bugfix for this issue and also fixes chat notification delay issue.
The new version should be available in the App Store later today or tomorrow :)

**Comment by chosebine501** [comment]
Good news !!

**Comment by chosebine501** [comment]
Hi,
We installed 12.1.0 there is no more notification and red icon working..

please it possible to return at 11?
