### ISSUE TITLE
No call notification

### ISSUE THREAD

**Issue by Ho551** [nextcloud/talk-ios#582]
## Steps to reproduce
1. app in background / inactive
2.
3.

### Expected behaviour
A notification / ring should appear when you receive a call

### Actual behaviour
Nothing happens. No call notification

## Device information

**Device:** iPhone XR

**iOS version:** 14.6

**Talk version:** 12.0.0

## Server information

**Nextcloud version:** 21.0.2
**Talk version:** 11.2.2

**Custom Signaling server configured:** no
**Custom TURN server configured:** yes/
**Custom STUN server configured:** yes/

Since the update to Talk 11 there have been problems with the notifications.
I am currently not receiving any call notification on my iPhone. The behavior was the same in the previous version.

If I can help in any way, please let me know

**Comment by Ivansss** [comment]
Hi @Ho551 :)
Do you receive notifications for chat messages?

**Comment by Ho551** [comment]
Hi @Ivansss :)
I get the chat notifications, but with a delay as in issue #580.
But I'm receiving no call notifications.
I don't know how far other apps play into this, so far I've always received the notifications on my iPad. (Only use the account on one device at a time).
I have uninstalled Talk and set it up again several times. The effect remains the same

**Comment by jakobroehrl** [comment]
I have similar issues with chat notifications on ios 12 and Server 21. 
Maybe the API change is the reason?

**Comment by Ivansss** [comment]
> But I'm receiving no call notifications.
> I don't know how far other apps play into this, so far I've always received the notifications on my iPad. (Only use the account on one device at a time).
> I have uninstalled Talk and set it up again several times. The effect remains the same

Does this happen only for a specific user or for every user in your NC instance? @Ho551 

> I have similar issues with chat notifications on ios 12 and Server 21.

What similar issues? 😅 Not receiving chat notifications or receiving them with a delay? @jakobroehrl 

Btw...Talk iOS version 12.1.0 was released yesterday. Chat notifications delay issue should be fixed in this version :)

**Comment by jakobroehrl** [comment]
Not receiving chat notifications from time to time since the 12 version.
Saw the new release, thanks. Testing if it solves the problem.

**Comment by chosebine501** [comment]
same issues

**Comment by DwinAnderson** [comment]
Earlier, before making update today (of version that was released 2 days ago) I had simular problems.
- I noticed that if mode "don't disturb" in ios is turned on, then there will be no notifications including ring notifications (but it's not a problem).
- Problems with ring notifications could also be because of when app installed and user logged in, app need permissions for mic and camera, but don't know how really it is true. Seems like it helped to make test call while both users in app and give all the necessary permissions.

**Comment by chosebine501** [comment]
> Earlier, before making update today (of version that was released 2 days ago) I had simular problems.
> 
> * I noticed that if mode "don't disturb" in ios is turned on, then there will be no notifications including ring notifications (but it's not a problem).
> * Problems with ring notifications could also be because of when app installed and user logged in, app need permissions for mic and camera, but don't know how really it is true. Seems like it helped to make test call while both users in app and give all the necessary permissions.

Yes I try this and it's help for us

**Comment by DwinAnderson** [comment]
Unfortunately faced with this problem, when app wasn’t launched :(

**Comment by Ho551** [comment]
Hi @Ivansss, 
the problem occurs with all users of my NC instance.
With the update to 12.1.0 the problem with the chat notifications is fixed. However, there is still no call notification when the app is running in the background.

If the user has received a chat notification shortly before, he will also receive a call notification afterwards. However, as soon as Talk has not been used for a while, call notification will no longer appear.

**Comment by Ho551** [comment]
Behavior also remains with updates from NC to version 21.0.3 and Talk 11.3.1

**Comment by kirtirc** [comment]
@Ivansss @Ho551 @jakobroehrl @chosebine501 @DwinAnderson 

Hello 
can you please help me
Nextcloud talk hosted in our server so where to uploaded push notification certificate  ?
Thanks in advance.

**Comment by SystemKeeper** [comment]
Hello @kirtirc, this issue is about missing call notifications, please don't mix topics.
Regarding push notification certificate see https://github.com/nextcloud/talk-ios/issues/560 for details.

**Comment by andyxheli** [comment]
@Ivansss same issue happens on all users from me. Someone called me today and I never got the notification that's I missed it or the ring

**Comment by AndyXheli** [comment]
@Ivansss I just upgraded to NC 22.1.1 running Talk Version 12.0.1 IOS Talk App Version is 12.2.0 and the notifiction are no longer working. When someone calls i never get the call notification and message either. This started to happen nice i updated to the new talk version

**Comment by Ho551** [comment]
Hi @Ivansss , I have updated NC to version 22.1.1, Talk to version 12.1.1 and iOS Talk to 12.2.0.
Occasional notifications now appear. Some notifications are not displayed, others are displayed. This applies to both chat and call notifications.
If the app is used on 2 iOS devices with the same account, no notification usually appears.

**Comment by andyxheli** [comment]
I just updated to talk server all on 12.1.1 and running talk iOS app on 12.2.0 and it now seems to be working! I did notice if I'm on a call on another device and someone sends me a message i don't get the notification since I'm already using the app and it's open but if I'm not not on a call I get notifications on all devices. Me too it sounds like the system knows you're on a call so it says no notifications

**Comment by AndyXheli** [comment]
Still having an issue getting call notifications all my users are not getting them. Will this be looked at anytime soon ?

**Comment by Ivansss** [comment]
Let's move the discussion to this other issue #595 because issues seems to be related.
