### ISSUE TITLE
Notifications repeating + no badge icon

### ISSUE THREAD

**Issue by gjongenelen** [nextcloud/talk-ios#584]
## Steps to reproduce
1. Install Nextcloud Talk app from store
2. Login and start chat from other user/device
3. Notifications come in delayed (#580), keep repeating until read and no icon badge appears

### Expected behaviour
Notifications come in 'faster', only once and icon badge shows number of unread messages.

### Actual behaviour
See step 3 in reproduction

## Device information

**Device:** iPhone XS
**iOS version:** iOS 14.6
**Talk version:** 12.0.0

## Server information

**Nextcloud version:** 20.0.10
**Talk version:** 10.0.8
**Custom Signaling server configured:** No
**Custom TURN server configured:** Yes (coturn)
**Custom STUN server configured:** No

### Server log (data/nextcloud.log)
No logs originating from Talk

**Comment by Ivansss** [comment]
Duplicated #580 #581
