### ISSUE TITLE
l10n: Need context for "Share pin location "

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/talk-ios#588]
https://github.com/nextcloud/talk-ios/blob/1c0a2235650a84a24c6f1823a090eacf2ce785b6/NextcloudTalk/ShareLocationViewController.m#L382

What kind of PIN is it? And how is it related to a location?

Please add some comment for translators.

**Comment by Ivansss** [comment]
@rakekniven you are right, context is really needed for that string.
Let me know what do you think about the comment I added for translators in #590 :)
