### ISSUE TITLE
Video call is not correctly closed -> no ringing

### ISSUE THREAD

**Issue by e-caste** [nextcloud/talk-ios#602]
## Steps to reproduce
1. Make a video call between iOS devices with the app, no browser involved.
2. When done, all participants end the call. This is correctly reported in the app (but in the browser the call remains open, see next point).
3. Log into Nextcloud from a desktop browser, see that the call is ongoing.
4. Wait a few seconds for Talk server to realize there is actually nobody in the video call, thus ending it and showing the message in the browser. (Ridiculous example below)
<img width="434" alt="-" src="https://user-images.githubusercontent.com/48513706/128198364-930a97de-83a8-4acb-babb-3a243f0f2f9b.png">

### Expected behaviour
The app should correctly terminate the call.

### Actual behaviour
The app incorrectly terminates the call, leading to 2 side effects:
1. The Talk server thinks there is an ongoing call
2. Due to point 1, there is no ringing on the iOS device for the same call (I haven't tested with other calls). After logging into Nextcloud from a desktop browser, the ringing immediately works again on the iOS device. Possibly related to #582 

## Device information

**Device:** iPhone 7

**iOS version:** 14.7.1

**Talk version:** 12.1.0

## Server information

**Nextcloud version:** (see admin overview page: `/index.php/settings/admin/overview`) 22.0.0 

**Talk version:** (see apps admin page: `/index.php/settings/apps`) 12.0.1 

**Custom Signaling server configured:** yes/no and version (see talk admin settings: `/index.php/settings/admin/talk#signaling_server`) no

**Custom TURN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#turn_server`) yes

**Custom STUN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#stun_server`) default STUN server

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by Ivansss** [comment]
> When done, all participants end the call. This is correctly reported in the app (but in the browser the call remains open, see next point).

What do you mean by correctly reported in the app? Do you see the call summary (the message showing the duration of the call) in the iOS app?

**Comment by e-caste** [comment]
@Ivansss 
> What do you mean by correctly reported in the app? Do you see the call summary (the message showing the duration of the call) in the iOS app?

Yes I mean that I see the duration of the video call when both parties leave it (below is an example). Though this screenshot if from September 13 and I haven't seen any other "Duration: X" messages in following calls while scrolling this conversation, except one for "Duration: 100+ hours" that I have triggered by logging into the website. With this I mean that I have made other calls, but they have never shown the "Duration: X" message at the end.

Note: all the video calls I am referring to are 1-on-1, iOS-to-iOS, no website involved.

![screenshot](https://user-images.githubusercontent.com/48513706/135245167-94418b86-d689-49f0-b2bc-e1669c5eac49.jpeg)

**Comment by Ivansss** [comment]
We have identified some issues with session cleanup when calls are not left correctly.

This PR should fix the problem with notifications https://github.com/nextcloud/spreed/pull/6300

But there is still a remaining issue with sessions cleanup that we will fix with a brackground job.
Here you can follow the progress of this issue: https://github.com/nextcloud/spreed/issues/6304

**Comment by e-caste** [comment]
Closing since this is fixed for me with:
- Nextcloud Talk Server v13.0.0
- Nextcloud Talk iOS v13.0.0
