### ISSUE TITLE
Reconnect on failed connection

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/talk-ios#603]
Currently if you lose an internet connect or in poor cell areas while being on a call you get a failed connection error and you have to leave and rejoin the call. I think it would be a good idea to have an option to hit reconnect or for it to automatically connect 
![21-08-14 08-37-24 5605](https://user-images.githubusercontent.com/59488153/129448228-f151ee76-4ac3-4c80-a705-cfe60e480550.png)

**Comment by AndyXheli** [comment]
I was doing some more troubleshooting and looks like when connecting to the wifi while being on the call the talk app will not redirect the call via wifi but still continues to run over the mobile so while being on the call i turned off my cell data and of cause i lose the connect at first is said connecting to "username" and it said call failed to connect "username" i think it would be nice to have something in the app that takes analyzes the connection and if wifi is connected it should always try to route  the calls via wifi or and if you disconnect from while route calls via mobile data.

**Comment by AndyXheli** [comment]
Hi @SystemKeeper just wanted to see if this would be something in the future or should i close this issue ?

**Comment by SystemKeeper** [comment]
Hey @andyxheli,
it's interesting, I have never experienced this behaviour (without loosing the whole connectivity). That being said, we could definitely think about having something like a reconnect option if we go to a failed state.

**Comment by SystemKeeper** [comment]
We recently added quite some changes to the call reliability and reconnecting feature. Please retest with 20.0.1 once it is out, it should improve the issues you're seeing.
