### ISSUE TITLE
Show error: This Nextcloud instance is currently in maintenance mode

### ISSUE THREAD

**Issue by vikstrom** [nextcloud/talk-ios#636]
**Problem**
For users of the app it's not very helpful to receive  "Unkown error occured" when opening a conversation while the nextcloud instance is in maintenance mode.

**Feature request**
Produce an error more akin to the one seen in the browser.

Of course, I don't know the issues involved with implementing this but it would be nice.

**Comment by SystemKeeper** [comment]
Thanks for the feature request! I‘ll close this in favor of https://github.com/nextcloud/talk-ios/issues/576
