### ISSUE TITLE
Question: Retina Display Resolution

### ISSUE THREAD

**Issue by sunjam** [nextcloud/talk-ios#92]
Resolution of the Talk app appears lower resolution on iOS retina display than the standard Nextcloud app.
![b419fd67-12d6-41d0-9fed-e0c88e7aff86](https://user-images.githubusercontent.com/1787238/39220046-3cb5ec2a-47e3-11e8-8459-d6e929e0b600.jpeg)

**Comment by Ivansss** [comment]
What elements seems to be in lower resolution? 🤔
Calls, Contacts and Settings have icons for every possible resolution (1x, 2x, 3x).

**Comment by sunjam** [comment]
What I meant to say is the spacing is very large between each contact/icon/setting.  Font is very large on each number, displaying only up to 11 on the screen at a time.  Wondering if there is a way to visually condense this more.

**Comment by Ivansss** [comment]
The spacing between tabs (Calls/Contacts/Settings) is the default one.
Fonts and height used in tableview cells is a custom one.
At the moment there is no difference between iPhones and iPads UI.
An iPad specific UI will be implemented in the future.
