### ISSUE TITLE
Suggestion: Audio only calls

### ISSUE THREAD

**Issue by sunjam** [nextcloud/talk-ios#93]
I can find no way to make audio only calls from the app.  Didn’t see a Github issue, so adding it here.  Cheers.

**Comment by Ivansss** [comment]
Audio-only calls were implemented in #75 
Once you tap on a call the following dialog will be shown (since version 1.3.0):

![img_0146](https://user-images.githubusercontent.com/4638605/39235178-81271658-4875-11e8-884f-b98623f0657c.PNG)

'Call' option is the way to make audio-only calls.
