### ISSUE TITLE
App crash when clicking on settings

### ISSUE THREAD

**Issue by bonanza123** [nextcloud/talk-ios#96]
I have the following issue:
I used an app token to login, which didn't seem to be an issue at first (no error was given). But I couldn't see any contacts. In the server logs I saw that the login failed. Nevertheless, the ios app opens without prompting me to fix the credentials. Instead, it shows the normal screen but without any contacts. When click on "settings" to change the user/password, the app crashes. Removing/reinstalling the app doesn't seem to solve the problem: It tries to connect again with the (wrong) password/app token.

**Comment by Ivansss** [comment]
Hi @bonanza123,
Could you tell us which Nextcloud Talk (server app and iOS app) versions are you using?

**Comment by bonanza123** [comment]
@Ivansss 
thanks for your reply.
Its NC Talk version 1.3.0 on ios 11.2.5
The NC version reported in the admin section of the server is: 13.0.1 and its running NC Talk 3.1.0

**Comment by Ivansss** [comment]
What about the Nextcloud Talk app version in the server?
You could check it in 'Apps' sections.

**Comment by bonanza123** [comment]
@Ivansss its 3.1.0, sorry.

**Comment by Ivansss** [comment]
Thanks for the info :)
Could you try to connect with a different user to the app?

**Comment by bonanza123** [comment]
The problem is that I don't know how to do that: When clicking the "settings" pane the app crashes. Also reinstalling the app doesn't allow me to change the user.

**Comment by Ivansss** [comment]
Oh I see...
We are working on a fix for that.
Thanks for the report! :)

**Comment by Ivansss** [comment]
Hi @bonanza123 
Could you provide us a test account from your NC server?
You can send it to ivan AT nextcloud DOT com

**Comment by bonanza123** [comment]
@Ivansss I just created an account for you. I hope you have received a corresponding mail.

**Comment by Ivansss** [comment]
I did 😉  thanks!

**Comment by bonanza123** [comment]
Please note that I used an app-token when the error occurred (not sure if that's important or not)

**Comment by Ivansss** [comment]
We are going to release 1.3.1 version today that will include the fix for the crash in Settings.
I was able to use the test account you provide us with the iOS app using both ways to log in (normal credentials and app tokens}.
Once you update the app to 1.3.1 you will be able to log out.
After that, try to log in again and it should work just fine.
1.3.1 will be a hotfix release, but we will keep trying to figure out how you reach to that inconsistent state.

**Comment by bonanza123** [comment]
@Ivansss thanks, I was able to update this morning and change the account.
However, I cannot see calls that are shown on the browser (e.g. group calls that I joined beforehand on the browser). Also I cannot see any contacts. Should I open a separate issue for that?

**Comment by Ivansss** [comment]
Hi @bonanza123,
Could you try with different users?
I could see calls and contacts with the test user you provide us.
Also could you try to log in with normal credentials?

**Comment by Ivansss** [comment]
@bonanza123 feel free to open a new issue if you keep having issues.
Closing this one since crash in Settings was fixed.
