### ISSUE TITLE
Ring tone

### ISSUE THREAD

**Issue by Ammar7347** [nextcloud/talk-ios#97]
Hi,
I use iPhone and was surprised to know the fact that this app doesn't have any ringtone. It just gives a standard iOS notification only once which most of the time is difficult to hear. I saw the same issue opened for talk-android here: (https://github.com/nextcloud/talk-android/issues/104) and I tried the android app and I do get ringtone notifications. So, It would be awesome if the same thing can be done with the iOS app.

**Comment by Ammar7347** [comment]
No response from anyone including the devs?

**Comment by Ivansss** [comment]
Hi @Ammar7347,
Sorry for the late reply.
We have planned some changes in the push notification proxy we use in nextcloud.
Once these changes are implemented, we will be able to use PushKit + CallKit #17 in this app.
This will allow the app to have ringtones and a nice user experience.

**Comment by bitsandnumbers** [comment]
Hi @Ivansss , any news on this ?

**Comment by Ivansss** [comment]
Hi @bitsandnumbers,
We could not make the changes required on the server for Nextcloud 14 but they are on the roadmap for 15 :)

**Comment by bitsandnumbers** [comment]
Arf, too bad. I was going to switch from Signal to Talk with 14, but I guess I'll have to wait a little longer :-)

Thanks for your answer.

**Comment by Ammar7347** [comment]
@Ivansss NC15 is out and I see CallKit is still under development. Can you please provide us with an ETA? I really want to ditch everything including whatsapp and telegram for Talk. The Android app is fine but I don't have android anymore so I really need this feature so badly.

**Comment by Ivansss** [comment]
CallKit integration will be available soon (February).
The required changes in our push proxy for this feature have been already implemented and they are Nextcloud server independent.

**Comment by Ivansss** [comment]
Closing this since CallKit is available in version 3.3.0
