### ISSUE TITLE
Nextcloud Talk crashes, when trying to add contact in contact

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/talk-ios#98]
Nextcloud Talk crashes, when trying to add contact in contact Context. This happens everytime.

**Comment by Githopp192** [comment]
Related to Nextcloud 13.0.2, IOS 11.3

**Comment by Githopp192** [comment]
App version IOS 1.3.1, App Version NC: 3.2.0

**Comment by Ivansss** [comment]
Hi @Githopp192 ,
What do you mean by 'add contact in contact Context'?
It's not possible to add contacts in the contacts section.
Do you mean adding a participant to a room/call?

**Comment by Githopp192** [comment]
Hi Ivansss

When opening the iPhone "Nextcloud Talk", i can choose (at the botton) between "Calls" "Contacts" and "Settings" .. when i choose "Contacts", i can scroll down the white page and search-context will appear at the top. There i can search for a user name. When i do this, the user name with the Full name will appear.
So far so good. As soon i move with my finger to that contact, the app will crash.  Maybe i missed something to correct configure onto the NC Web.

**Comment by Ivansss** [comment]
Don't you see any contacts when you go to "Contacts" section? (without doing any search)

**Comment by Githopp192** [comment]
No .. i do not .. but may be this has to do with the NC Configuration Setup .. under the "Share"context in the NC GUI .. i did disable the Flag "Auto-Completion of username ..." .. if this is disabled, one/you need to enter the complete User Name .. this is under the Context "Federated-Cloud Sharing" (see the Picture) .. 

So .. when i enable this Flag "(Auto-Completion...") .. i do open the Nextcloud-Talk App on my iPhone .. the i can see all the contacts from the NC. Also i can search (as i did in the past), click on the name .. and now i short option menu will appear, where i'm be able to call this person.

So .. it seems .. it is maybe an application bug, which will not consider, when the Flag "Auto-Completion" is disabled ..

**Comment by Githopp192** [comment]
sorry .. the relevant flag is NOT under the "Federated-Cloud Sharing" context .. it is under the normal Share Dialog ...see new picture ..

**Comment by Ivansss** [comment]
Is that the only flag you disabled?
Just tried disabling that flag and contacts are only visible when searching as you described.
But the app is not crashing when selecting one of the results of the search.

**Comment by Githopp192** [comment]
These are the flags ... under share context.. hope it‘s ok for you in German, otherwise i could switch to engllish, if this would be an issue 4u.

[image1.jpeg]

Von meinem iPhone ge[image2.jpeg]

Am 11.05.2018 um 17:04 schrieb Ivan Sein <notifications@github.com<mailto:notifications@github.com>>:


Is that the only flag you disabled?
Just tried disabling that flag and contacts are only visible when searching as you described.
But the app is not crashing when selecting one of the results of the search.

**Comment by Githopp192** [comment]
Hi Ivansss, did you receive the Pictures with the flags i enabled/disabled ?

When not, i can resend those information.

**Comment by Ivansss** [comment]
Hi @Githopp192 ,
I can't see the image of your last message.
Neither the ones in the other comments where you say "See picture" 😬

**Comment by Githopp192** [comment]
![img_1033](https://user-images.githubusercontent.com/32612067/40052717-f5a4149e-583e-11e8-8237-0cae76e9c99c.jpg)
![img_1032](https://user-images.githubusercontent.com/32612067/40052719-f5c5f4ce-583e-11e8-9a94-0ee9c93aa6c0.jpg)

Hope this works now

**Comment by Ivansss** [comment]
Thanks :)
I have tried the app with the exact same configuration, but I couldn't make the app crash when selecting one of the contacts.
So when you have the autocompletion flag disable the app crashes when selecting a contact and when the flag is enable it works?

**Comment by Githopp192** [comment]
very welcome Ivansss 👍 

yes ... if it works at all (with making conf calls to athers) ... i can not fully say .. but at least .. yes .. 
i can choose contact as soon i did disable the "autocompl. flag" .. and the app then does not crash .. 

To exclude other things .. i once did reboot my iPhone .. but this did not help

**Comment by Githopp192** [comment]
very welcome Ivansss 👍
yes ... if it works at all (with making conf calls to athers) ... i can not fully say .. but at least .. yes ..
i can choose contact as soon i did enable the "autocompl. flag" .. and the app then does not crash ..
To exclude other things .. i once did reboot my iPhone .. but this did not help

**Comment by Ivansss** [comment]
Could you send me an email with the test account credentials to ivan@nextcloud.com? :)

**Comment by Githopp192** [comment]
Hi Ivan

i did open an account for you (check your Mail Inbox)

Thx 4 supporting Nextcloud !

Have a good start into the week
